"""
Audio fixture metadata for Tasmeeʿ integration tests.

Source: EveryAyah.com
Reciter: Alafasy_128kbps
License: Free for personal and educational use

This file is auto-generated by download_fixtures.py
"""

RECITER = "Alafasy_128kbps"

# Verse texts (with tashkeel)
VERSE_TEXTS = {(1, 1): 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ', (1, 2): 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ', (1, 3): 'الرَّحْمَٰنِ الرَّحِيمِ', (1, 4): 'مَالِكِ يَوْمِ الدِّينِ', (1, 5): 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ', (1, 6): 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ', (1, 7): 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ', (112, 1): 'قُلْ هُوَ اللَّهُ أَحَدٌ', (112, 2): 'اللَّهُ الصَّمَدُ', (112, 3): 'لَمْ يَلِدْ وَلَمْ يُولَدْ', (112, 4): 'وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ', (2, 255): 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ'}

# Test verses available
TEST_VERSES = [(1, 1, 'bismillah'), (1, 2, 'alhamdulillah'), (1, 3, 'arrahman'), (1, 4, 'maliki'), (1, 5, 'iyyaka'), (1, 6, 'ihdina'), (1, 7, 'sirat'), (112, 1, 'ikhlas_1'), (112, 2, 'ikhlas_2'), (112, 3, 'ikhlas_3'), (112, 4, 'ikhlas_4'), (2, 255, 'ayat_kursi')]


def get_audio_path(surah: int, ayah: int, format: str = "wav") -> str:
    """Get path to audio file for a verse."""
    from pathlib import Path
    base_dir = Path(__file__).parent

    for s, a, desc in TEST_VERSES:
        if s == surah and a == ayah:
            return str(base_dir / f"{s:03d}_{a:03d}_{desc}.{format}")

    raise ValueError(f"No audio fixture for {surah}:{ayah}")


def get_verse_text(surah: int, ayah: int) -> str:
    """Get expected text for a verse."""
    return VERSE_TEXTS.get((surah, ayah), "")
