"""
Grounded per-verse Ask AI endpoints (Phase Y).

Replaces the ungrounded /tafseer/llm/* family for the in-verse AI Assistant.
Every response is generated by the existing RAG pipeline (`RAGPipeline.query`)
so the answer is backed by retrieved tafseer chunks with mandatory citations,
confidence, and safe-refusal — fully compliant with the project's
"RAG-only, never invent tafsir" rule (see CLAUDE.md → "Do Not Generate
Tafsir or Religious Answers").

Endpoints:
    POST /api/v1/rag/verse/ask           — answer a free-form question about a verse
    POST /api/v1/rag/verse/summarize     — summarize tafsir for the verse
    POST /api/v1/rag/verse/explain-word  — explain a single word from the verse
    GET  /api/v1/rag/verse/suggested-questions — bilingual suggested-questions list

Safety:
    - Surah / ayah are validated (1..114, ≥1) before retrieval.
    - The question is prefixed with the verse reference so HybridRetriever's
      verse-anchored fast path scopes evidence to the right ayahs.
    - Answers that produce no citations fall through to the standard
      safe-refusal status="no_verified_source" with the bilingual message.
    - No new prompts. No edits to backend/app/rag/prompts.py.
"""
from __future__ import annotations

import asyncio
import logging
import re
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field, field_validator
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.rate_limit import rag_rate_limit
from app.db.database import get_async_session
from app.rag.pipeline import RAGPipeline

logger = logging.getLogger(__name__)

router = APIRouter()


# =============================================================================
# Constants
# =============================================================================

_VERSE_QUERY_TIMEOUT_SECONDS = 60.0
_VERSE_MAX_SOURCES = 5
_VERSE_PATTERN = re.compile(r"^[1-9][0-9]{0,2}$")


# =============================================================================
# Schemas
# =============================================================================


def _validate_surah_ayah(surah: int, ayah_start: int, ayah_end: Optional[int]) -> None:
    if not 1 <= surah <= 114:
        raise HTTPException(
            status_code=400,
            detail={
                "error_code": "invalid_surah",
                "message_en": "Surah must be between 1 and 114",
                "message_ar": "رقم السورة يجب أن يكون بين 1 و 114",
            },
        )
    if ayah_start < 1:
        raise HTTPException(
            status_code=400,
            detail={
                "error_code": "invalid_ayah",
                "message_en": "ayah_start must be ≥ 1",
                "message_ar": "رقم الآية يجب أن يكون ≥ 1",
            },
        )
    if ayah_end is not None and ayah_end < ayah_start:
        raise HTTPException(
            status_code=400,
            detail={
                "error_code": "invalid_ayah_range",
                "message_en": "ayah_end must be ≥ ayah_start",
                "message_ar": "نهاية الآية يجب أن تكون ≥ بدايتها",
            },
        )


def _verse_ref_str(surah: int, ayah_start: int, ayah_end: Optional[int]) -> str:
    if ayah_end and ayah_end != ayah_start:
        return f"{surah}:{ayah_start}-{ayah_end}"
    return f"{surah}:{ayah_start}"


def _compose_anchored_query(
    *,
    surah: int,
    ayah_start: int,
    ayah_end: Optional[int],
    question: str,
    language: str,
) -> str:
    """
    Build a query that includes the explicit surah:ayah reference so
    HybridRetriever's verse-anchored fast path kicks in. We DO NOT inject
    Arabic Quran text into the prompt — only the reference number.
    """
    ref = _verse_ref_str(surah, ayah_start, ayah_end)
    if language == "ar":
        return f"الآية {ref}: {question.strip()}"
    return f"Verse {ref}: {question.strip()}"


class VerseAskRequest(BaseModel):
    """Free-form question about a specific verse."""

    surah: int = Field(..., ge=1, le=114, description="Surah number")
    ayah_start: int = Field(..., ge=1, description="Starting ayah")
    ayah_end: Optional[int] = Field(default=None, ge=1, description="Optional end ayah")
    question: str = Field(..., min_length=3, max_length=1000)
    language: str = Field(default="ar", pattern="^(ar|en)$")
    preferred_sources: List[str] = Field(default_factory=list)
    max_sources: int = Field(default=_VERSE_MAX_SOURCES, ge=1, le=10)

    @field_validator("question")
    @classmethod
    def _clean_question(cls, v: str) -> str:
        v = v.strip()
        if len(v) < 3:
            raise ValueError("Question must be at least 3 characters")
        return v


class VerseSummarizeRequest(BaseModel):
    """Summarize the tafsir for a specific verse."""

    surah: int = Field(..., ge=1, le=114)
    ayah_start: int = Field(..., ge=1)
    ayah_end: Optional[int] = Field(default=None, ge=1)
    language: str = Field(default="ar", pattern="^(ar|en)$")
    preferred_sources: List[str] = Field(default_factory=list)
    max_sources: int = Field(default=_VERSE_MAX_SOURCES, ge=1, le=10)


class VerseExplainWordRequest(BaseModel):
    """Explain a single word from a specific verse using grounded sources."""

    surah: int = Field(..., ge=1, le=114)
    ayah_start: int = Field(..., ge=1)
    ayah_end: Optional[int] = Field(default=None, ge=1)
    word: str = Field(..., min_length=1, max_length=80)
    language: str = Field(default="ar", pattern="^(ar|en)$")
    preferred_sources: List[str] = Field(default_factory=list)

    @field_validator("word")
    @classmethod
    def _clean_word(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("Word must not be empty")
        return v


class SuggestedQuestion(BaseModel):
    id: str
    text: str
    language: str


class SuggestedQuestionsResponse(BaseModel):
    surah: int
    ayah_start: int
    ayah_end: Optional[int] = None
    language: str
    questions: List[SuggestedQuestion]


# =============================================================================
# Suggested questions — server-side templates
# =============================================================================

_SUGGESTED_QUESTION_TEMPLATES = {
    "ar": [
        {"id": "revelation", "text": "ما سبب نزول هذه الآية؟"},
        {"id": "lessons", "text": "ما الدروس والعبر المستفادة من هذه الآية؟"},
        {"id": "context", "text": "ما علاقة هذه الآية بما قبلها وما بعدها؟"},
    ],
    "en": [
        {"id": "revelation", "text": "What is the occasion of revelation for this verse?"},
        {"id": "lessons", "text": "What lessons can we learn from this verse?"},
        {"id": "context", "text": "How does this verse relate to what comes before and after it?"},
    ],
}


# =============================================================================
# Helpers
# =============================================================================


async def _run_pipeline(
    session: AsyncSession,
    *,
    question: str,
    language: str,
    preferred_sources: List[str],
    max_sources: int,
):
    pipeline = RAGPipeline(session)
    return await asyncio.wait_for(
        pipeline.query(
            question=question,
            language=language,
            include_scholarly_debate=True,
            preferred_sources=preferred_sources,
            max_sources=max_sources,
        ),
        timeout=_VERSE_QUERY_TIMEOUT_SECONDS,
    )


def _attach_verse_metadata(payload: dict, *, surah: int, ayah_start: int, ayah_end: Optional[int]) -> dict:
    payload["verse"] = {
        "surah": surah,
        "ayah_start": ayah_start,
        "ayah_end": ayah_end,
        "reference": _verse_ref_str(surah, ayah_start, ayah_end),
    }
    return payload


def _attach_suggestions(payload: dict, language: str) -> dict:
    """If the grounded response is empty or refused, surface the suggested
    questions so the UI can offer next-step prompts to the user."""
    if payload.get("status") == "no_verified_source" or not payload.get("citations"):
        payload.setdefault(
            "suggested_questions",
            _SUGGESTED_QUESTION_TEMPLATES.get(language, _SUGGESTED_QUESTION_TEMPLATES["en"]),
        )
    return payload


# =============================================================================
# Routes
# =============================================================================


@router.post("/verse/ask")
async def verse_ask(
    body: VerseAskRequest,
    session: AsyncSession = Depends(get_async_session),
    _rate: None = Depends(rag_rate_limit),
):
    """Answer a free-form question about a specific verse.

    Returns a GroundedResponse (dict). Always includes citations array;
    when no evidence is available the response carries
    `status="no_verified_source"` with the bilingual safe-refusal text
    and a `suggested_questions` list.
    """
    _validate_surah_ayah(body.surah, body.ayah_start, body.ayah_end)

    anchored = _compose_anchored_query(
        surah=body.surah,
        ayah_start=body.ayah_start,
        ayah_end=body.ayah_end,
        question=body.question,
        language=body.language,
    )

    try:
        result = await _run_pipeline(
            session,
            question=anchored,
            language=body.language,
            preferred_sources=body.preferred_sources,
            max_sources=body.max_sources,
        )
    except asyncio.TimeoutError:
        logger.error("verse_ask timeout for %s", _verse_ref_str(body.surah, body.ayah_start, body.ayah_end))
        raise HTTPException(
            status_code=504,
            detail={
                "error_code": "timeout",
                "message_en": "Request timed out, please try again",
                "message_ar": "انتهت مهلة الطلب، حاول مرة أخرى",
            },
        )

    payload = result.to_dict() if hasattr(result, "to_dict") else dict(result)
    payload = _attach_verse_metadata(payload, surah=body.surah, ayah_start=body.ayah_start, ayah_end=body.ayah_end)
    payload = _attach_suggestions(payload, body.language)
    return payload


@router.post("/verse/summarize")
async def verse_summarize(
    body: VerseSummarizeRequest,
    session: AsyncSession = Depends(get_async_session),
    _rate: None = Depends(rag_rate_limit),
):
    """Summarize the tafsir corpus for a specific verse, grounded in citations."""
    _validate_surah_ayah(body.surah, body.ayah_start, body.ayah_end)

    if body.language == "ar":
        question = "لخّص تفسير هذه الآية باختصار مع ذكر المعنى والدروس المستفادة."
    else:
        question = "Summarize the tafsir of this verse concisely, including its meaning and main lessons."

    anchored = _compose_anchored_query(
        surah=body.surah,
        ayah_start=body.ayah_start,
        ayah_end=body.ayah_end,
        question=question,
        language=body.language,
    )

    try:
        result = await _run_pipeline(
            session,
            question=anchored,
            language=body.language,
            preferred_sources=body.preferred_sources,
            max_sources=body.max_sources,
        )
    except asyncio.TimeoutError:
        raise HTTPException(
            status_code=504,
            detail={
                "error_code": "timeout",
                "message_en": "Request timed out, please try again",
                "message_ar": "انتهت مهلة الطلب، حاول مرة أخرى",
            },
        )

    payload = result.to_dict() if hasattr(result, "to_dict") else dict(result)
    payload = _attach_verse_metadata(payload, surah=body.surah, ayah_start=body.ayah_start, ayah_end=body.ayah_end)
    payload = _attach_suggestions(payload, body.language)
    return payload


@router.post("/verse/explain-word")
async def verse_explain_word(
    body: VerseExplainWordRequest,
    session: AsyncSession = Depends(get_async_session),
    _rate: None = Depends(rag_rate_limit),
):
    """Explain a word from a verse using retrieved tafsir context."""
    _validate_surah_ayah(body.surah, body.ayah_start, body.ayah_end)

    if body.language == "ar":
        question = f"اشرح معنى الكلمة «{body.word}» في هذه الآية شرحاً مختصراً مع ذكر المعنى اللغوي ودلالتها في السياق."
    else:
        question = f"Explain the word \"{body.word}\" in this verse — its linguistic meaning and contextual significance."

    anchored = _compose_anchored_query(
        surah=body.surah,
        ayah_start=body.ayah_start,
        ayah_end=body.ayah_end,
        question=question,
        language=body.language,
    )

    try:
        result = await _run_pipeline(
            session,
            question=anchored,
            language=body.language,
            preferred_sources=body.preferred_sources,
            max_sources=_VERSE_MAX_SOURCES,
        )
    except asyncio.TimeoutError:
        raise HTTPException(
            status_code=504,
            detail={
                "error_code": "timeout",
                "message_en": "Request timed out, please try again",
                "message_ar": "انتهت مهلة الطلب، حاول مرة أخرى",
            },
        )

    payload = result.to_dict() if hasattr(result, "to_dict") else dict(result)
    payload["word"] = body.word
    payload = _attach_verse_metadata(payload, surah=body.surah, ayah_start=body.ayah_start, ayah_end=body.ayah_end)
    payload = _attach_suggestions(payload, body.language)
    return payload


@router.get("/verse/suggested-questions", response_model=SuggestedQuestionsResponse)
def verse_suggested_questions(
    surah: int = Query(..., ge=1, le=114),
    ayah_start: int = Query(..., ge=1),
    ayah_end: Optional[int] = Query(None, ge=1),
    language: str = Query("ar", pattern="^(ar|en)$"),
) -> SuggestedQuestionsResponse:
    """Return bilingual templated suggested questions for the verse.

    The list is intentionally short (3 entries) so the UI can render them
    as one-click chips beside the question input.
    """
    _validate_surah_ayah(surah, ayah_start, ayah_end)
    raw = _SUGGESTED_QUESTION_TEMPLATES.get(language, _SUGGESTED_QUESTION_TEMPLATES["en"])
    return SuggestedQuestionsResponse(
        surah=surah,
        ayah_start=ayah_start,
        ayah_end=ayah_end,
        language=language,
        questions=[SuggestedQuestion(id=q["id"], text=q["text"], language=language) for q in raw],
    )
