"""
Phase 6: Quran Review Task API

File-backed review workflow for Quran-sensitive content pending scholarly review.

PERSISTENCE NOTE:
  Tasks are read from backend/app/data/review_tasks.json (generated by
  scripts/generate-review-tasks.ts).  Decisions are stored in
  backend/app/data/review_decisions.json.  This is an in-memory/file-backed
  stub appropriate for a development/review workflow.  In production, decisions
  should be migrated to the PostgreSQL verification_queue table.

SAFETY RULES:
  - Approval requires reviewerId, notes, and explicit decision status.
  - Rejection requires notes.
  - Decisions never modify Quran text, story text, or KG edge data.
  - All decisions are audit-logged with timestamp.
  - Rejected content must not display as approved.
  - humanReviewRequired safeguard is preserved in all responses.

Endpoints:
  GET  /api/v1/admin/review/tasks           — list tasks with filters
  GET  /api/v1/admin/review/tasks/{task_id} — get task detail
  POST /api/v1/admin/review/tasks/{task_id}/decision — submit decision
  GET  /api/v1/admin/review/stats           — dashboard statistics
"""
import json
import os
import logging
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query, Path as FPath
from pydantic import BaseModel, Field, field_validator

logger = logging.getLogger(__name__)

router = APIRouter()

# ---------------------------------------------------------------------------
# File paths
# ---------------------------------------------------------------------------

_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "app" / "data"
_TASKS_FILE = _DATA_DIR / "review_tasks.json"
_DECISIONS_FILE = _DATA_DIR / "review_decisions.json"

# ---------------------------------------------------------------------------
# Valid enums
# ---------------------------------------------------------------------------

VALID_CONTENT_TYPES = {
    "story_segment",
    "related_story",
    "kg_relation",
    "source_evidence",
    "disagreement_note",
}

VALID_STATUSES = {"pending", "approved", "rejected", "changes_requested"}
VALID_PRIORITIES = {"low", "medium", "high"}
VALID_DECISION_STATUSES = {"approved", "rejected", "changes_requested"}


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------

class QuranRefResponse(BaseModel):
    surahNumber: int
    ayahStart: int
    ayahEnd: Optional[int] = None


class ReviewDecisionResponse(BaseModel):
    status: str
    notes: str
    reviewerId: str
    reviewerName: Optional[str] = None
    reviewedAt: str


class ReviewTaskResponse(BaseModel):
    id: str
    contentType: str
    contentId: str
    status: str
    priority: str
    language: str
    reviewerId: Optional[str] = None
    reviewerName: Optional[str] = None
    createdAt: str
    updatedAt: str
    reviewedAt: Optional[str] = None
    sourceIds: List[str]
    quranReferences: List[QuranRefResponse]
    decision: Optional[ReviewDecisionResponse] = None
    warnings: List[str]
    humanReviewRequired: bool
    summaryEnglish: Optional[str] = None
    storyId: Optional[str] = None
    segmentId: Optional[str] = None
    disagreementNotes: Optional[List[str]] = None


class ReviewTaskListResponse(BaseModel):
    tasks: List[ReviewTaskResponse]
    total: int
    offset: int
    limit: int


class SubmitDecisionRequest(BaseModel):
    """
    Request body for submitting a review decision.

    Rules:
    - status must be 'approved', 'rejected', or 'changes_requested'
    - notes are required for all decisions
    - reviewerId is required
    - Decision never modifies Quran text or story data
    """
    status: str = Field(..., description="approved | rejected | changes_requested")
    notes: str = Field(..., min_length=10, description="Required review notes (min 10 chars)")
    reviewerId: str = Field(..., min_length=1, description="Reviewer identifier")
    reviewerName: Optional[str] = Field(None, description="Human-readable reviewer name")

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        if v not in VALID_DECISION_STATUSES:
            raise ValueError(f"status must be one of: {', '.join(sorted(VALID_DECISION_STATUSES))}")
        return v

    @field_validator("notes")
    @classmethod
    def validate_notes(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("notes cannot be empty")
        return v.strip()


class ReviewStatsResponse(BaseModel):
    total: int
    pending: int
    approved: int
    rejected: int
    changes_requested: int
    by_content_type: Dict[str, int]
    by_priority: Dict[str, int]
    high_priority: int
    with_disagreement_notes: int
    human_review_required: int


# ---------------------------------------------------------------------------
# File-backed data store
# ---------------------------------------------------------------------------

class ReviewTaskStore:
    """
    Reads tasks from review_tasks.json and persists decisions to
    review_decisions.json.

    Thread-safety: FastAPI runs each request in a single thread within an
    async event loop; file reads are atomic enough for a review workflow.
    For production scale, replace with PostgreSQL VerificationQueue.
    """

    def __init__(self):
        self._tasks: Dict[str, dict] = {}
        self._decisions: Dict[str, dict] = {}
        self._loaded = False

    def _load(self) -> None:
        if self._loaded:
            return

        # Load tasks
        if _TASKS_FILE.exists():
            try:
                raw = json.loads(_TASKS_FILE.read_text(encoding="utf-8"))
                for task in raw.get("tasks", []):
                    self._tasks[task["id"]] = task
                logger.info("Loaded %d review tasks from %s", len(self._tasks), _TASKS_FILE)
            except Exception as exc:
                logger.error("Failed to load review_tasks.json: %s", exc)
        else:
            logger.warning("review_tasks.json not found at %s — run generate-review-tasks.ts", _TASKS_FILE)

        # Load decisions
        if _DECISIONS_FILE.exists():
            try:
                self._decisions = json.loads(_DECISIONS_FILE.read_text(encoding="utf-8"))
                logger.info("Loaded %d review decisions from %s", len(self._decisions), _DECISIONS_FILE)
            except Exception as exc:
                logger.error("Failed to load review_decisions.json: %s", exc)

        # Merge decisions into tasks
        for task_id, decision in self._decisions.items():
            if task_id in self._tasks:
                self._tasks[task_id]["decision"] = decision
                self._tasks[task_id]["status"] = decision["status"]
                self._tasks[task_id]["reviewedAt"] = decision["reviewedAt"]
                self._tasks[task_id]["reviewerId"] = decision["reviewerId"]
                self._tasks[task_id]["reviewerName"] = decision.get("reviewerName")
                self._tasks[task_id]["updatedAt"] = decision["reviewedAt"]

        self._loaded = True

    def _save_decisions(self) -> None:
        _DATA_DIR.mkdir(parents=True, exist_ok=True)
        _DECISIONS_FILE.write_text(
            json.dumps(self._decisions, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

    def get_all(
        self,
        content_type: Optional[str] = None,
        status: Optional[str] = None,
        priority: Optional[str] = None,
        source_id: Optional[str] = None,
        has_disagreement: Optional[bool] = None,
        human_review_required: Optional[bool] = None,
        story_id: Optional[str] = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[dict], int]:
        self._load()

        results = list(self._tasks.values())

        if content_type:
            results = [t for t in results if t.get("contentType") == content_type]
        if status:
            results = [t for t in results if t.get("status") == status]
        if priority:
            results = [t for t in results if t.get("priority") == priority]
        if source_id:
            results = [t for t in results if source_id in t.get("sourceIds", [])]
        if has_disagreement is not None:
            results = [
                t for t in results
                if bool(t.get("disagreementNotes")) == has_disagreement
            ]
        if human_review_required is not None:
            results = [
                t for t in results
                if t.get("humanReviewRequired") == human_review_required
            ]
        if story_id:
            results = [t for t in results if t.get("storyId") == story_id]

        # Sort: high priority first, then by contentType, then by createdAt
        priority_order = {"high": 0, "medium": 1, "low": 2}
        results.sort(key=lambda t: (
            priority_order.get(t.get("priority", "low"), 3),
            t.get("contentType", ""),
            t.get("createdAt", ""),
        ))

        total = len(results)
        return results[offset : offset + limit], total

    def get_by_id(self, task_id: str) -> Optional[dict]:
        self._load()
        return self._tasks.get(task_id)

    def submit_decision(
        self,
        task_id: str,
        decision_status: str,
        notes: str,
        reviewer_id: str,
        reviewer_name: Optional[str] = None,
    ) -> dict:
        self._load()

        task = self._tasks.get(task_id)
        if not task:
            raise ValueError(f"Task {task_id} not found")

        now = datetime.now(timezone.utc).isoformat()

        decision = {
            "status": decision_status,
            "notes": notes,
            "reviewerId": reviewer_id,
            "reviewerName": reviewer_name,
            "reviewedAt": now,
        }

        # Update in-memory task
        task["decision"] = decision
        task["status"] = decision_status
        task["reviewedAt"] = now
        task["reviewerId"] = reviewer_id
        task["reviewerName"] = reviewer_name
        task["updatedAt"] = now

        # Persist decision
        self._decisions[task_id] = decision
        self._save_decisions()

        logger.info(
            "Review decision %s for task %s by reviewer %s",
            decision_status, task_id, reviewer_id,
        )

        return task

    def get_stats(self) -> dict:
        self._load()
        tasks = list(self._tasks.values())

        by_ct: Dict[str, int] = {}
        by_pr: Dict[str, int] = {}

        for t in tasks:
            ct = t.get("contentType", "unknown")
            by_ct[ct] = by_ct.get(ct, 0) + 1
            pr = t.get("priority", "unknown")
            by_pr[pr] = by_pr.get(pr, 0) + 1

        return {
            "total": len(tasks),
            "pending": sum(1 for t in tasks if t.get("status") == "pending"),
            "approved": sum(1 for t in tasks if t.get("status") == "approved"),
            "rejected": sum(1 for t in tasks if t.get("status") == "rejected"),
            "changes_requested": sum(1 for t in tasks if t.get("status") == "changes_requested"),
            "by_content_type": by_ct,
            "by_priority": by_pr,
            "high_priority": sum(1 for t in tasks if t.get("priority") == "high"),
            "with_disagreement_notes": sum(1 for t in tasks if t.get("disagreementNotes")),
            "human_review_required": sum(1 for t in tasks if t.get("humanReviewRequired")),
        }


# Singleton store (loaded lazily on first request)
_store = ReviewTaskStore()


def _task_to_response(task: dict) -> ReviewTaskResponse:
    decision_data = task.get("decision")
    decision = None
    if decision_data:
        decision = ReviewDecisionResponse(
            status=decision_data.get("status", ""),
            notes=decision_data.get("notes", ""),
            reviewerId=decision_data.get("reviewerId", ""),
            reviewerName=decision_data.get("reviewerName"),
            reviewedAt=decision_data.get("reviewedAt", ""),
        )

    refs = [
        QuranRefResponse(
            surahNumber=r["surahNumber"],
            ayahStart=r["ayahStart"],
            ayahEnd=r.get("ayahEnd"),
        )
        for r in task.get("quranReferences", [])
    ]

    return ReviewTaskResponse(
        id=task["id"],
        contentType=task.get("contentType", ""),
        contentId=task.get("contentId", ""),
        status=task.get("status", "pending"),
        priority=task.get("priority", "medium"),
        language=task.get("language", "both"),
        reviewerId=task.get("reviewerId"),
        reviewerName=task.get("reviewerName"),
        createdAt=task.get("createdAt", ""),
        updatedAt=task.get("updatedAt", ""),
        reviewedAt=task.get("reviewedAt"),
        sourceIds=task.get("sourceIds", []),
        quranReferences=refs,
        decision=decision,
        warnings=task.get("warnings", []),
        humanReviewRequired=task.get("humanReviewRequired", True),
        summaryEnglish=task.get("summaryEnglish"),
        storyId=task.get("storyId"),
        segmentId=task.get("segmentId"),
        disagreementNotes=task.get("disagreementNotes"),
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/review/tasks", response_model=ReviewTaskListResponse)
async def list_review_tasks(
    content_type: Optional[str] = Query(None, description="Filter by content type"),
    status: Optional[str] = Query(None, description="Filter by status"),
    priority: Optional[str] = Query(None, description="Filter by priority"),
    source_id: Optional[str] = Query(None, description="Filter by source ID"),
    has_disagreement: Optional[bool] = Query(None, description="Filter tasks with disagreement notes"),
    human_review_required: Optional[bool] = Query(None, description="Filter by humanReviewRequired"),
    story_id: Optional[str] = Query(None, description="Filter by story ID"),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    """
    List review tasks with optional filters.

    Returns tasks ordered by priority (high first), then contentType, then creation date.
    """
    if content_type and content_type not in VALID_CONTENT_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid content_type. Must be one of: {', '.join(sorted(VALID_CONTENT_TYPES))}",
        )
    if status and status not in VALID_STATUSES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid status. Must be one of: {', '.join(sorted(VALID_STATUSES))}",
        )
    if priority and priority not in VALID_PRIORITIES:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid priority. Must be one of: {', '.join(sorted(VALID_PRIORITIES))}",
        )

    tasks, total = _store.get_all(
        content_type=content_type,
        status=status,
        priority=priority,
        source_id=source_id,
        has_disagreement=has_disagreement,
        human_review_required=human_review_required,
        story_id=story_id,
        limit=limit,
        offset=offset,
    )

    return ReviewTaskListResponse(
        tasks=[_task_to_response(t) for t in tasks],
        total=total,
        offset=offset,
        limit=limit,
    )


@router.get("/review/tasks/{task_id}", response_model=ReviewTaskResponse)
async def get_review_task(
    task_id: str = FPath(..., description="Review task ID"),
):
    """Get a single review task by ID."""
    task = _store.get_by_id(task_id)
    if not task:
        raise HTTPException(status_code=404, detail=f"Review task {task_id!r} not found")
    return _task_to_response(task)


@router.post("/review/tasks/{task_id}/decision", response_model=ReviewTaskResponse)
async def submit_task_decision(
    task_id: str = FPath(..., description="Review task ID"),
    body: SubmitDecisionRequest = ...,
):
    """
    Submit a review decision for a task.

    Safety rules:
    - All decisions require reviewerId and notes (min 10 chars)
    - Decision only updates review metadata — never Quran text or story content
    - Audit trail: every decision is persisted with reviewerId + timestamp
    - Approved tasks gain reviewerId/reviewedAt/notes in the decision field
    - Rejected tasks are flagged and must not be shown as approved in the UI

    Arabic notice:
    لا يعتمد هذا المحتوى إلا بعد مراجعة علمية موثقة.
    (This content is not approved until documented scholarly review is completed.)
    """
    try:
        updated = _store.submit_decision(
            task_id=task_id,
            decision_status=body.status,
            notes=body.notes,
            reviewer_id=body.reviewerId,
            reviewer_name=body.reviewerName,
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

    return _task_to_response(updated)


@router.get("/review/stats", response_model=ReviewStatsResponse)
async def get_review_stats():
    """
    Get review task dashboard statistics.

    Returns counts by status, content type, priority, and special flags.
    """
    stats = _store.get_stats()
    return ReviewStatsResponse(**stats)


@router.get("/review/content-types")
async def get_content_types():
    """Get valid content types with labels."""
    labels = {
        "story_segment": {"ar": "مقطع القصة", "en": "Story Segment"},
        "related_story": {"ar": "قصة مرتبطة", "en": "Related Story"},
        "kg_relation": {"ar": "صلة المعرفة", "en": "KG Relation"},
        "source_evidence": {"ar": "دليل المصدر", "en": "Source Evidence"},
        "disagreement_note": {"ar": "ملاحظة خلاف", "en": "Disagreement Note"},
    }
    return {
        "content_types": [
            {"value": ct, "labels": labels.get(ct, {"ar": ct, "en": ct})}
            for ct in sorted(VALID_CONTENT_TYPES)
        ]
    }
