"""
Phase H — Quranic Vocabulary / Gharib Al-Quran (live DB)

Endpoints:
  GET /vocabulary/lookup?word={word}          — search by Arabic text
  GET /vocabulary/by-ref?sura={n}&aya={n}&pos={n} — in-verse word lookup
  GET /vocabulary/status                      — module availability
  GET /vocabulary/sources                     — lexicon catalogue

Safety rule: Word meanings must NEVER be generated by AI alone.
Every entry in vocabulary_entries requires a verified source_id.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from sqlalchemy import select, func, case, or_
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional

from app.core.rate_limit import vocab_rate_limit
from app.db.database import get_async_session
from app.models.vocabulary import VocabEntry

router = APIRouter()

# ---------------------------------------------------------------------------
# Safe-refusal messages (shown when no DB entry exists)
# ---------------------------------------------------------------------------

_SAFE_REFUSAL_EN = (
    "No verified lexical source is available for this word yet. "
    "Word meanings are not generated by AI alone — every entry must come from "
    "a verified classical Arabic lexicon. Run backend/scripts/seed_vocabulary_qac.py "
    "to seed the Quranic Arabic Corpus data."
)

_SAFE_REFUSAL_AR = (
    "لا يتوفر مصدر موثوق لمعنى هذه المفردة حالياً. "
    "لا يُولَّد معنى الكلمة بالذكاء الاصطناعي وحده — يجب أن تصدر كل مدخلات "
    "المعجم عن مصدر موثوق. نفِّذ seed_vocabulary_qac.py لإضافة بيانات المدوّنة."
)


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------

class VocabularyResponse(BaseModel):
    word: str
    status: str          # "found" | "no_verified_source"
    message_en: str
    message_ar: str
    source_id: Optional[str] = None
    source_title_en: Optional[str] = None
    root: Optional[str] = None
    pattern: Optional[str] = None
    pos_tag: Optional[str] = None
    meaning_en: Optional[str] = None
    meaning_ar: Optional[str] = None
    example_verses: list[str] = []


class VocabularyStatusResponse(BaseModel):
    module: str
    available: bool
    reason: str
    entry_count: int
    planned_sources: list[str]
    message_en: str
    message_ar: str


class LexiconSource(BaseModel):
    source_id: str
    title_ar: str
    title_en: str
    author_ar: str
    author_en: str
    era_ar: str
    era_en: str
    focus_ar: str
    focus_en: str
    volumes: Optional[int] = None
    category: str   # 'arabic' | 'english' | 'digital'
    license: str
    status: str     # 'planned' | 'integrating' | 'available'


class LexiconSourcesResponse(BaseModel):
    sources: list[LexiconSource]
    total: int
    message_en: str
    message_ar: str


# ---------------------------------------------------------------------------
# Authenticated Sunni lexicon catalogue
# ---------------------------------------------------------------------------

_LEXICON_SOURCES: list[LexiconSource] = [
    LexiconSource(
        source_id='quranic_arabic_corpus',
        title_ar='مدوّنة القرآن العربية',
        title_en='Quranic Arabic Corpus (corpus.quran.com)',
        author_ar='قيس دوكس — جامعة ليدز',
        author_en='Kais Dukes, University of Leeds',
        era_ar='حديث (2009–2011)',
        era_en='Modern — 2009–2011',
        focus_ar='التحليل الصرفي والنحوي لكل كلمة قرآنية — 77,430 كلمة مُعرَبة بالكامل',
        focus_en='Word-by-word morphological and syntactic annotation of all 77,430 Quranic words',
        category='digital',
        license='GNU General Public License (GPL) — open source',
        status='available',
    ),
    LexiconSource(
        source_id='gharib_al_quran_ibn_qutaybah',
        title_ar='غريب القرآن',
        title_en="Ibn Qutayba's Gharib Al-Quran",
        author_ar='ابن قتيبة الدينوري',
        author_en='Ibn Qutayba al-Dinawari',
        era_ar='القرن الثالث الهجري (ت. 276 هـ)',
        era_en='3rd century AH — d. 276 AH / 889 CE',
        focus_ar='أقدم مصدر متخصص في شرح الكلمات القرآنية النادرة والغريبة',
        focus_en='Earliest specialized work on rare and unusual Quranic vocabulary',
        category='arabic',
        license='Public domain (d. 276 AH)',
        status='planned',
    ),
    LexiconSource(
        source_id='mufradat_al_raghib',
        title_ar='مفردات ألفاظ القرآن',
        title_en='Mufradat Al-Raghib Al-Isfahani',
        author_ar='الراغب الأصفهاني',
        author_en='Al-Raghib Al-Isfahani',
        era_ar='القرن الخامس الهجري (ت. 502 هـ)',
        era_en='5th century AH — d. 502 AH / 1108 CE',
        focus_ar='الأكثر توثيقاً في مصطلحات القرآن وألفاظه — مرجع أمهات التفاسير',
        focus_en='Most cited specialized lexicon of Quranic terminology — referenced by all major tafsir scholars',
        category='arabic',
        license='Public domain (d. 502 AH)',
        status='planned',
    ),
    LexiconSource(
        source_id='lisan_al_arab',
        title_ar='لسان العرب',
        title_en='Lisan Al-Arab (Ibn Manzur)',
        author_ar='ابن منظور',
        author_en='Ibn Manzur',
        era_ar='القرن السابع الهجري (ت. 711 هـ)',
        era_en='7th century AH — d. 711 AH / 1311 CE',
        focus_ar='أضخم المعاجم العربية الكلاسيكية — 20 مجلداً بالشواهد القرآنية والأدبية',
        focus_en='Largest classical Arabic dictionary — 20 volumes with extensive Quranic citations',
        volumes=20,
        category='arabic',
        license='Public domain (d. 711 AH)',
        status='planned',
    ),
    LexiconSource(
        source_id='qamus_al_muhit',
        title_ar='القاموس المحيط',
        title_en='Al-Qamus Al-Muhit (Al-Fayruzabadi)',
        author_ar='الفيروزآبادي',
        author_en='Al-Fayruzabadi',
        era_ar='القرن التاسع الهجري (ت. 817 هـ)',
        era_en='9th century AH — d. 817 AH / 1414 CE',
        focus_ar='معجم شامل أساسي في الدراسات اللغوية العربية',
        focus_en='Comprehensive classical Arabic lexicon — authoritative Sunni linguistic reference',
        category='arabic',
        license='Public domain (d. 817 AH)',
        status='planned',
    ),
    LexiconSource(
        source_id='al_nihaya_ibn_al_athir',
        title_ar='النهاية في غريب الحديث والأثر',
        title_en='Al-Nihaya fi Gharib Al-Hadith (Ibn Al-Athir)',
        author_ar='ابن الأثير الجزري',
        author_en='Ibn Al-Athir al-Jazari',
        era_ar='القرن السادس الهجري (ت. 606 هـ)',
        era_en='6th century AH — d. 606 AH / 1209 CE',
        focus_ar='الكلمات الغريبة في الحديث النبوي والقرآن الكريم',
        focus_en='Rare words in Hadith narrations and the Quran — authoritative Sunni reference',
        category='arabic',
        license='Public domain (d. 606 AH)',
        status='planned',
    ),
    LexiconSource(
        source_id='lanes_lexicon',
        title_ar='معجم لين العربي الإنجليزي',
        title_en="Lane's Arabic-English Lexicon",
        author_ar='إدوارد وليام لين',
        author_en='Edward William Lane',
        era_ar='القرن التاسع عشر الميلادي (ت. 1876 م)',
        era_en='19th century CE — d. 1876',
        focus_ar='المعجم العربي الإنجليزي الأشمل — 8 مجلدات مستندة إلى المصادر الكلاسيكية',
        focus_en='Most comprehensive Arabic-English lexicon — 8 volumes, fully grounded in classical sources',
        volumes=8,
        category='english',
        license='Public domain (19th century)',
        status='planned',
    ),
]

_PLANNED_SOURCES = [s.source_id for s in _LEXICON_SOURCES]

_SOURCE_TITLES: dict[str, str] = {s.source_id: s.title_en for s in _LEXICON_SOURCES}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

import re as _re

_DIACRITIC_RE = _re.compile(r'[ً-ٰٟۖ-ۜ۟-۪ۤۧۨ-ۭ]')


def _strip_diacritics(text: str) -> str:
    return _DIACRITIC_RE.sub('', text)


def _entry_to_response(entry: VocabEntry) -> VocabularyResponse:
    return VocabularyResponse(
        word=entry.word_ar,
        status='found',
        message_en='',
        message_ar='',
        source_id=entry.source_id,
        source_title_en=_SOURCE_TITLES.get(entry.source_id),
        root=entry.root_ar,
        pattern=entry.pattern_ar,
        pos_tag=entry.pos_tag,
        meaning_en=entry.meaning_en,
        meaning_ar=entry.meaning_ar,
        example_verses=[f'{entry.sura_no}:{entry.aya_no}'],
    )


def _not_found(word: str) -> VocabularyResponse:
    return VocabularyResponse(
        word=word,
        status='no_verified_source',
        message_en=_SAFE_REFUSAL_EN,
        message_ar=_SAFE_REFUSAL_AR,
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get('/lookup', response_model=VocabularyResponse)
async def vocabulary_lookup(
    word: str = Query(..., description='Arabic word to look up'),
    _rate: None = Depends(vocab_rate_limit),
    db: AsyncSession = Depends(get_async_session),
) -> VocabularyResponse:
    """
    Look up a Quranic word by its Arabic text.

    Matches against stored word forms (with and without diacritics).
    Returns the first matching entry from a verified lexicographic source.
    """
    word = word.strip()
    if not word:
        return _not_found('')

    bare = _strip_diacritics(word)

    # Single query: exact match preferred over bare-text match
    result = await db.execute(
        select(VocabEntry)
        .where(or_(VocabEntry.word_ar == word, VocabEntry.word_ar_bare == bare))
        .order_by(case((VocabEntry.word_ar == word, 0), else_=1))
        .limit(1)
    )
    entry = result.scalar_one_or_none()

    if entry is None:
        return _not_found(word)

    return _entry_to_response(entry)


@router.get('/by-ref', response_model=VocabularyResponse)
async def vocabulary_by_ref(
    sura: int = Query(..., ge=1, le=114, description='Surah number'),
    aya: int = Query(..., ge=1, description='Ayah number'),
    pos: int = Query(..., ge=1, description='Word position within the ayah (1-indexed)'),
    _rate: None = Depends(vocab_rate_limit),
    db: AsyncSession = Depends(get_async_session),
) -> VocabularyResponse:
    """
    Look up a word by its exact position in the Quran: sura:aya:word_position.

    This endpoint powers the inline hover-to-reveal feature in verse displays.
    """
    result = await db.execute(
        select(VocabEntry)
        .where(
            VocabEntry.sura_no == sura,
            VocabEntry.aya_no == aya,
            VocabEntry.word_position == pos,
        )
        .limit(1)
    )
    entry = result.scalar_one_or_none()

    if entry is None:
        return VocabularyResponse(
            word='',
            status='no_verified_source',
            message_en=_SAFE_REFUSAL_EN,
            message_ar=_SAFE_REFUSAL_AR,
        )

    return _entry_to_response(entry)


@router.get('/status', response_model=VocabularyStatusResponse)
async def vocabulary_status(
    db: AsyncSession = Depends(get_async_session),
) -> VocabularyStatusResponse:
    """Return module availability status, entry count, and source list."""
    count_result = await db.execute(select(func.count()).select_from(VocabEntry))
    entry_count: int = count_result.scalar_one() or 0

    available = entry_count > 0
    reason = (
        f'{entry_count:,} entries loaded from Quranic Arabic Corpus.'
        if available
        else 'No vocabulary entries in database. Run seed_vocabulary_qac.py to populate.'
    )

    return VocabularyStatusResponse(
        module='vocabulary',
        available=available,
        reason=reason,
        entry_count=entry_count,
        planned_sources=_PLANNED_SOURCES,
        message_en='' if available else _SAFE_REFUSAL_EN,
        message_ar='' if available else _SAFE_REFUSAL_AR,
    )


@router.get('/sources', response_model=LexiconSourcesResponse)
async def vocabulary_sources() -> LexiconSourcesResponse:
    """Return the full catalogue of authenticated Sunni lexicographic sources."""
    return LexiconSourcesResponse(
        sources=_LEXICON_SOURCES,
        total=len(_LEXICON_SOURCES),
        message_en='Sources marked available are loaded in the database.',
        message_ar='المصادر المُشار إليها بـ available مُحمَّلة في قاعدة البيانات.',
    )
