"""
Phase F — Quranic Vocabulary / Gharib Al-Quran
Safe placeholder endpoint.

No verified word-level lexical data exists on this platform yet.
Returns a structured safe-refusal response so that:
  - The UI shows the correct 'coming soon / no source' state
  - Tests can verify safe-refusal behavior
  - The schema is established for when a verified lexicon is integrated

Safety rule: Word meanings must NEVER be generated by AI alone.
Every entry requires a source_id pointing to a verified classical lexicon.
"""
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional

router = APIRouter()

_SAFE_REFUSAL_EN = (
    "No verified lexical source is available for this word yet. "
    "Word meanings are not generated by AI alone — every entry must come from "
    "a verified classical Arabic lexicon (e.g., Lisan Al-Arab or "
    "Mufradat Al-Raghib Al-Isfahani). This feature is planned."
)

_SAFE_REFUSAL_AR = (
    "لا يتوفر مصدر موثوق لمعنى هذه المفردة حالياً. "
    "لا يُولَّد معنى الكلمة بالذكاء الاصطناعي وحده — يجب أن تصدر كل مدخلات "
    "المعجم عن مصدر موثوق كلسان العرب أو مفردات الراغب الأصفهاني. "
    "هذه الميزة مخطط لها مستقبلاً."
)

_PLANNED_SOURCES = ["lisan_al_arab", "mufradat_al_raghib", "qamus_al_muhit", "lanes_lexicon"]


class VocabularyResponse(BaseModel):
    word: str
    status: str          # "no_verified_source" | "found"
    message_en: str
    message_ar: str
    source_id: Optional[str] = None
    root: Optional[str] = None
    meaning_en: Optional[str] = None
    meaning_ar: Optional[str] = None
    example_verses: list[str] = []


class VocabularyStatusResponse(BaseModel):
    module: str
    available: bool
    reason: str
    planned_sources: list[str]
    message_en: str
    message_ar: str


@router.get("/lookup", response_model=VocabularyResponse)
async def vocabulary_lookup(word: str) -> VocabularyResponse:
    """
    Look up a Quranic word.

    Returns safe-refusal until a verified lexical data source is integrated.
    See docs/quran-vocabulary-module-plan.md for the full implementation plan.
    """
    return VocabularyResponse(
        word=word,
        status="no_verified_source",
        message_en=_SAFE_REFUSAL_EN,
        message_ar=_SAFE_REFUSAL_AR,
    )


@router.get("/status", response_model=VocabularyStatusResponse)
async def vocabulary_status() -> VocabularyStatusResponse:
    """Return module availability status and planned source list."""
    return VocabularyStatusResponse(
        module="vocabulary",
        available=False,
        reason="No verified lexical source integrated yet.",
        planned_sources=_PLANNED_SOURCES,
        message_en=_SAFE_REFUSAL_EN,
        message_ar=_SAFE_REFUSAL_AR,
    )
