"""
Vocabulary (Word Meanings) Model — Phase H.

Stores word-by-word morphological entries sourced from the Quranic Arabic
Corpus (QAC) and classical lexicons.

Every entry MUST carry a source_id pointing to a verified lexicographic
source registered in the platform's source registry.  Meanings must never
be generated by AI alone.
"""
from datetime import datetime

from sqlalchemy import Column, Integer, SmallInteger, Text, String, DateTime, Index, UniqueConstraint

from app.db.database import Base


class VocabEntry(Base):
    __tablename__ = "vocabulary_entries"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Verse-word location (QAC chapter:verse:word indexing, 1-based)
    sura_no = Column(SmallInteger, nullable=False)
    aya_no = Column(SmallInteger, nullable=False)
    word_position = Column(SmallInteger, nullable=False)  # 1-indexed

    # Arabic word forms
    word_ar = Column(Text, nullable=False)       # Full diacritised form
    word_ar_bare = Column(Text, nullable=False)  # Without diacritics

    # Morphology
    root_ar = Column(Text, nullable=True)        # Arabic-script root
    pattern_ar = Column(Text, nullable=True)     # Morphological weight pattern
    pos_tag = Column(String(50), nullable=True)  # POS from grammar model enums

    # Meanings
    meaning_en = Column(Text, nullable=True)
    meaning_ar = Column(Text, nullable=True)

    # Provenance — required
    source_id = Column(Text, nullable=False)

    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    reviewed_at = Column(DateTime, nullable=True)
    reviewer_id = Column(Text, nullable=True)

    __table_args__ = (
        UniqueConstraint("sura_no", "aya_no", "word_position", name="uq_vocab_location"),
        Index("ix_vocab_root", "root_ar"),
        Index("ix_vocab_word_bare", "word_ar_bare"),
        Index("ix_vocab_source", "source_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<VocabEntry {self.sura_no}:{self.aya_no}:{self.word_position} "
            f"word={self.word_ar!r} source={self.source_id!r}>"
        )
