/**
 * Quran Memorization Intelligence — Type System
 *
 * Purpose: help memorizers avoid confusion between similar ayat,
 * track story recurrence across surahs, and navigate phrase anchors.
 *
 * Safety rules:
 * - All auto-generated links carry reviewStatus = "needs_review"
 * - Similarity reasons must be descriptive, never interpretive
 * - Difference notes must be factual (text difference), never theological
 * - Evidence refs required for any interpretive claim
 */

import type { AyahRef, BilingualText, EvidenceReference } from './surahAtlas';
import type { SunniReviewStatus } from './quranStory';

// ---------------------------------------------------------------------------
// Memorization Link Types
// ---------------------------------------------------------------------------

export type MemorizationLinkType =
  | 'similar_opening'
  | 'similar_ending'
  | 'similar_phrase'
  | 'repeated_story'
  | 'repeated_dialogue'
  | 'same_prophet_different_surah'
  | 'same_theme_different_surah'
  | 'near_duplicate_structure'
  | 'contrast_pair'
  | 'chronological_story_sequence'
  | 'same_command'
  | 'same_dua'
  | 'same_warning'
  | 'same_reward'
  | 'same_punishment';

// ---------------------------------------------------------------------------
// Memorization Link — connects two ayat or two surah ranges
// ---------------------------------------------------------------------------

export interface MemorizationLink {
  id: string;
  sourceAyah: AyahRef;
  targetAyah: AyahRef;
  sourceSurah: number;
  targetSurah: number;
  linkType: MemorizationLinkType;
  similarityReason: BilingualText;
  memorizerHint: BilingualText;
  differenceNote: BilingualText;
  riskOfConfusion: 'high' | 'medium' | 'low';
  evidenceRefs: EvidenceReference[];
  autoGenerated: boolean;
  reviewStatus: SunniReviewStatus;
  humanReviewRequired: boolean;
}

// ---------------------------------------------------------------------------
// Confusion Pair — two ayat easily confused during memorization
// ---------------------------------------------------------------------------

export interface ConfusionPair {
  id: string;
  ayahA: AyahRef;
  ayahB: AyahRef;
  confusionReason: BilingualText;
  keyDifference: BilingualText;
  memorizerTip: BilingualText;
  riskLevel: 'high' | 'medium' | 'low';
  autoGenerated: boolean;
  reviewStatus: SunniReviewStatus;
  humanReviewRequired: boolean;
}

// ---------------------------------------------------------------------------
// Repeated Phrase Entry — a phrase that appears multiple times in the Quran
// ---------------------------------------------------------------------------

export interface QuranRepeatedPhrase {
  id: string;
  phraseArabic: string;
  transliteration?: string;
  meaningEn: string;
  meaningAr: string;
  occurrences: AyahRef[];
  themeLabel: BilingualText;
  memorizerNote: BilingualText;
  autoGenerated: boolean;
  reviewStatus: SunniReviewStatus;
}

// ---------------------------------------------------------------------------
// Story Recurrence Map — where a story appears across surahs
// ---------------------------------------------------------------------------

export interface StoryRecurrenceEntry {
  storyId: string;
  titleEn: string;
  titleAr: string;
  surahOccurrences: Array<{
    surahNumber: number;
    surahName: string;
    ayahRange: AyahRef;
    coverageNote: BilingualText;
  }>;
  dominantSurahNumber: number;
  totalOccurrences: number;
  reviewStatus: SunniReviewStatus;
}

// ---------------------------------------------------------------------------
// Surah Connection — memorization-aware link between two surahs
// ---------------------------------------------------------------------------

export interface SurahMemorizationConnection {
  id: string;
  surahA: number;
  surahB: number;
  connectionType: MemorizationLinkType;
  description: BilingualText;
  confidence: 'high' | 'medium' | 'low';
  reviewStatus: SunniReviewStatus;
  humanReviewRequired: boolean;
}

// ---------------------------------------------------------------------------
// Memorization Intelligence Collection
// ---------------------------------------------------------------------------

export interface MemorizationIntelligence {
  version: string;
  generatedAt: string;
  links: MemorizationLink[];
  confusionPairs: ConfusionPair[];
  repeatedPhrases: QuranRepeatedPhrase[];
  storyRecurrences: StoryRecurrenceEntry[];
  surahConnections: SurahMemorizationConnection[];
  reviewNote: BilingualText;
}
