"""add_story_atlas_tables

Revision ID: 8c162ed15d9b
Revises: ce5e28ac4034
Create Date: 2026-01-04 18:58:19.825941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c162ed15d9b'
down_revision: Union[str, None] = 'ce5e28ac4034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_clusters',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title_ar', sa.String(length=300), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('short_title_ar', sa.String(length=100), nullable=True),
    sa.Column('short_title_en', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('main_persons', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('groups', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('places', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.Column('era_basis', sa.String(length=20), nullable=True),
    sa.Column('time_description_ar', sa.String(length=200), nullable=True),
    sa.Column('time_description_en', sa.String(length=200), nullable=True),
    sa.Column('ayah_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_sura', sa.Integer(), nullable=True),
    sa.Column('total_verses', sa.Integer(), nullable=True),
    sa.Column('suras_mentioned', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('summary_ar', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('lessons_ar', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('lessons_en', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_category', 'story_clusters', ['category'], unique=False)
    op.create_index('ix_cluster_era', 'story_clusters', ['era'], unique=False)
    op.create_index('ix_cluster_primary_sura', 'story_clusters', ['primary_sura'], unique=False)
    op.create_table('cluster_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_cluster_id', sa.String(length=100), nullable=False),
    sa.Column('target_cluster_id', sa.String(length=100), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('label_ar', sa.String(length=200), nullable=True),
    sa.Column('label_en', sa.String(length=200), nullable=True),
    sa.Column('shared_persons', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('shared_places', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('shared_themes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('evidence_chunk_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_cluster_id'], ['story_clusters.id'], ),
    sa.ForeignKeyConstraint(['target_cluster_id'], ['story_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_cluster_id', 'target_cluster_id', 'connection_type', name='uq_cluster_connection')
    )
    op.create_index('ix_cluster_conn_source', 'cluster_connections', ['source_cluster_id'], unique=False)
    op.create_index('ix_cluster_conn_target', 'cluster_connections', ['target_cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_connections_source_cluster_id'), 'cluster_connections', ['source_cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_connections_target_cluster_id'), 'cluster_connections', ['target_cluster_id'], unique=False)
    op.create_table('story_events',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('narrative_role', sa.String(length=50), nullable=False),
    sa.Column('chronological_index', sa.Integer(), nullable=False),
    sa.Column('is_entry_point', sa.Boolean(), nullable=True),
    sa.Column('sura_no', sa.Integer(), nullable=False),
    sa.Column('aya_start', sa.Integer(), nullable=False),
    sa.Column('aya_end', sa.Integer(), nullable=False),
    sa.Column('summary_ar', sa.Text(), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('memorization_cue_ar', sa.String(length=200), nullable=True),
    sa.Column('memorization_cue_en', sa.String(length=200), nullable=True),
    sa.Column('semantic_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('jsonb_array_length(evidence) >= 1', name='ck_event_has_evidence'),
    sa.ForeignKeyConstraint(['cluster_id'], ['story_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_chronological', 'story_events', ['cluster_id', 'chronological_index'], unique=False)
    op.create_index('ix_event_cluster', 'story_events', ['cluster_id'], unique=False)
    op.create_index('ix_event_location', 'story_events', ['sura_no', 'aya_start'], unique=False)
    op.create_index('ix_event_role', 'story_events', ['narrative_role'], unique=False)
    op.create_index(op.f('ix_story_events_cluster_id'), 'story_events', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_story_events_sura_no'), 'story_events', ['sura_no'], unique=False)
    op.create_table('event_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_event_id', sa.String(length=150), nullable=False),
    sa.Column('target_event_id', sa.String(length=150), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('is_chronological', sa.Boolean(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('justification_en', sa.Text(), nullable=True),
    sa.Column('justification_ar', sa.Text(), nullable=True),
    sa.Column('evidence_chunk_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['story_events.id'], ),
    sa.ForeignKeyConstraint(['target_event_id'], ['story_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_conn_source', 'event_connections', ['source_event_id'], unique=False)
    op.create_index('ix_event_conn_target', 'event_connections', ['target_event_id'], unique=False)
    op.create_index(op.f('ix_event_connections_source_event_id'), 'event_connections', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_event_connections_target_event_id'), 'event_connections', ['target_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_connections_target_event_id'), table_name='event_connections')
    op.drop_index(op.f('ix_event_connections_source_event_id'), table_name='event_connections')
    op.drop_index('ix_event_conn_target', table_name='event_connections')
    op.drop_index('ix_event_conn_source', table_name='event_connections')
    op.drop_table('event_connections')
    op.drop_index(op.f('ix_story_events_sura_no'), table_name='story_events')
    op.drop_index(op.f('ix_story_events_cluster_id'), table_name='story_events')
    op.drop_index('ix_event_role', table_name='story_events')
    op.drop_index('ix_event_location', table_name='story_events')
    op.drop_index('ix_event_cluster', table_name='story_events')
    op.drop_index('ix_event_chronological', table_name='story_events')
    op.drop_table('story_events')
    op.drop_index(op.f('ix_cluster_connections_target_cluster_id'), table_name='cluster_connections')
    op.drop_index(op.f('ix_cluster_connections_source_cluster_id'), table_name='cluster_connections')
    op.drop_index('ix_cluster_conn_target', table_name='cluster_connections')
    op.drop_index('ix_cluster_conn_source', table_name='cluster_connections')
    op.drop_table('cluster_connections')
    op.drop_index('ix_cluster_primary_sura', table_name='story_clusters')
    op.drop_index('ix_cluster_era', table_name='story_clusters')
    op.drop_index('ix_cluster_category', table_name='story_clusters')
    op.drop_table('story_clusters')
    # ### end Alembic commands ###
