"""add_story_graph_enhanced_fields

Revision ID: ce5e28ac4034
Revises: 4fdb53c55f30
Create Date: 2026-01-04 18:03:29.782083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce5e28ac4034'
down_revision: Union[str, None] = '4fdb53c55f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_story_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_story_id', sa.String(length=50), nullable=False),
    sa.Column('target_story_id', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('label_ar', sa.String(length=200), nullable=True),
    sa.Column('label_en', sa.String(length=200), nullable=True),
    sa.Column('explanation_ar', sa.Text(), nullable=True),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('evidence_chunk_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('shared_themes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('shared_figures', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('array_length(evidence_chunk_ids, 1) >= 1', name='ck_cross_story_has_evidence'),
    sa.ForeignKeyConstraint(['source_story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['target_story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_story_connections_source_story_id'), 'cross_story_connections', ['source_story_id'], unique=False)
    op.create_index(op.f('ix_cross_story_connections_target_story_id'), 'cross_story_connections', ['target_story_id'], unique=False)
    op.create_index('ix_cross_story_source', 'cross_story_connections', ['source_story_id'], unique=False)
    op.create_index('ix_cross_story_target', 'cross_story_connections', ['target_story_id'], unique=False)
    op.add_column('story_connections', sa.Column('edge_type', sa.String(length=50), nullable=False))
    op.add_column('story_connections', sa.Column('is_chronological', sa.Boolean(), nullable=True))
    op.add_column('story_connections', sa.Column('justification_ar', sa.Text(), nullable=True))
    op.add_column('story_connections', sa.Column('justification_en', sa.Text(), nullable=True))
    op.add_column('story_connections', sa.Column('evidence_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('story_connections', sa.Column('cross_story', sa.Boolean(), nullable=True))
    op.alter_column('story_connections', 'connection_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('ix_connection_chronological', 'story_connections', ['is_chronological'], unique=False)
    op.create_index('ix_connection_edge_type', 'story_connections', ['edge_type'], unique=False)
    op.add_column('story_segments', sa.Column('chronological_index', sa.Integer(), nullable=True))
    op.add_column('story_segments', sa.Column('narrative_role', sa.String(length=50), nullable=True))
    op.add_column('story_segments', sa.Column('semantic_tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('story_segments', sa.Column('title_ar', sa.String(length=200), nullable=True))
    op.add_column('story_segments', sa.Column('title_en', sa.String(length=200), nullable=True))
    op.add_column('story_segments', sa.Column('memorization_cue_ar', sa.String(length=200), nullable=True))
    op.add_column('story_segments', sa.Column('memorization_cue_en', sa.String(length=200), nullable=True))
    op.add_column('story_segments', sa.Column('evidence_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('story_segments', sa.Column('evidence_chunk_ids', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('story_segments', sa.Column('is_entry_point', sa.Boolean(), nullable=True))
    op.create_index('ix_segment_chronological', 'story_segments', ['story_id', 'chronological_index'], unique=False)
    op.create_index('ix_segment_narrative_role', 'story_segments', ['narrative_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segment_narrative_role', table_name='story_segments')
    op.drop_index('ix_segment_chronological', table_name='story_segments')
    op.drop_column('story_segments', 'is_entry_point')
    op.drop_column('story_segments', 'evidence_chunk_ids')
    op.drop_column('story_segments', 'evidence_sources')
    op.drop_column('story_segments', 'memorization_cue_en')
    op.drop_column('story_segments', 'memorization_cue_ar')
    op.drop_column('story_segments', 'title_en')
    op.drop_column('story_segments', 'title_ar')
    op.drop_column('story_segments', 'semantic_tags')
    op.drop_column('story_segments', 'narrative_role')
    op.drop_column('story_segments', 'chronological_index')
    op.drop_index('ix_connection_edge_type', table_name='story_connections')
    op.drop_index('ix_connection_chronological', table_name='story_connections')
    op.alter_column('story_connections', 'connection_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('story_connections', 'cross_story')
    op.drop_column('story_connections', 'evidence_details')
    op.drop_column('story_connections', 'justification_en')
    op.drop_column('story_connections', 'justification_ar')
    op.drop_column('story_connections', 'is_chronological')
    op.drop_column('story_connections', 'edge_type')
    op.drop_index('ix_cross_story_target', table_name='cross_story_connections')
    op.drop_index('ix_cross_story_source', table_name='cross_story_connections')
    op.drop_index(op.f('ix_cross_story_connections_target_story_id'), table_name='cross_story_connections')
    op.drop_index(op.f('ix_cross_story_connections_source_story_id'), table_name='cross_story_connections')
    op.drop_table('cross_story_connections')
    # ### end Alembic commands ###
