"""Add provenance and audit log

Revision ID: f796d0030737
Revises: 001_initial
Create Date: 2026-01-03 14:06:58.967746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f796d0030737'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('cdn_url', sa.Text(), nullable=True),
    sa.Column('version_tag', sa.String(length=100), nullable=True),
    sa.Column('data_hash', sa.String(length=64), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['tafseer_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_verses_juz_no'), 'quran_verses', ['juz_no'], unique=False)
    op.create_index(op.f('ix_quran_verses_page_no'), 'quran_verses', ['page_no'], unique=False)
    op.create_index(op.f('ix_story_connections_source_segment_id'), 'story_connections', ['source_segment_id'], unique=False)
    op.create_index(op.f('ix_story_connections_target_segment_id'), 'story_connections', ['target_segment_id'], unique=False)
    op.create_index(op.f('ix_story_segments_story_id'), 'story_segments', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_segments_sura_no'), 'story_segments', ['sura_no'], unique=False)
    op.create_index(op.f('ix_tafseer_chunks_source_id'), 'tafseer_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_tafseer_chunks_sura_no'), 'tafseer_chunks', ['sura_no'], unique=False)
    op.add_column('tafseer_sources', sa.Column('cdn_url', sa.Text(), nullable=True))
    op.add_column('tafseer_sources', sa.Column('version_tag', sa.String(length=100), nullable=True))
    op.add_column('tafseer_sources', sa.Column('retrieval_timestamp', sa.DateTime(), nullable=True))
    op.add_column('tafseer_sources', sa.Column('data_hash', sa.String(length=64), nullable=True))
    op.add_column('tafseer_sources', sa.Column('ayah_count', sa.Integer(), nullable=True))
    op.add_column('tafseer_sources', sa.Column('license_type', sa.String(length=100), nullable=True))
    op.add_column('tafseer_sources', sa.Column('license_verified', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_translations_language'), 'translations', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_language'), table_name='translations')
    op.drop_column('tafseer_sources', 'license_verified')
    op.drop_column('tafseer_sources', 'license_type')
    op.drop_column('tafseer_sources', 'ayah_count')
    op.drop_column('tafseer_sources', 'data_hash')
    op.drop_column('tafseer_sources', 'retrieval_timestamp')
    op.drop_column('tafseer_sources', 'version_tag')
    op.drop_column('tafseer_sources', 'cdn_url')
    op.drop_index(op.f('ix_tafseer_chunks_sura_no'), table_name='tafseer_chunks')
    op.drop_index(op.f('ix_tafseer_chunks_source_id'), table_name='tafseer_chunks')
    op.drop_index(op.f('ix_story_segments_sura_no'), table_name='story_segments')
    op.drop_index(op.f('ix_story_segments_story_id'), table_name='story_segments')
    op.drop_index(op.f('ix_story_connections_target_segment_id'), table_name='story_connections')
    op.drop_index(op.f('ix_story_connections_source_segment_id'), table_name='story_connections')
    op.drop_index(op.f('ix_quran_verses_page_no'), table_name='quran_verses')
    op.drop_index(op.f('ix_quran_verses_juz_no'), table_name='quran_verses')
    op.drop_table('ingestion_audit_log')
    # ### end Alembic commands ###
