/**
 * Quran Memorization Intelligence — Seed Data
 *
 * CONTENT POLICY:
 * - All links are auto-generated from structural/textual analysis
 * - Every entry carries reviewStatus: 'needs_review' and humanReviewRequired: true
 * - similarityReason describes textual structure only, never theological interpretation
 * - differenceNote is factual (what the text says differently), not interpretive
 * - Evidence refs will be filled during scholarly review
 *
 * These links help memorizers:
 * 1. Avoid confusing similar ayat
 * 2. Use story recurrence as memory anchors
 * 3. Leverage repeated phrases across surahs
 */

import type {
  MemorizationLink,
  ConfusionPair,
  QuranRepeatedPhrase,
  StoryRecurrenceEntry,
  MemorizationIntelligence,
} from '../types/quranMemorization';

// ---------------------------------------------------------------------------
// High-priority confusion pairs — similar ayat that memorizers often confuse
// ---------------------------------------------------------------------------

export const CONFUSION_PAIRS: ConfusionPair[] = [
  {
    id: 'cp_baqara_7_vs_baqara_18',
    ayahA: { surah: 2, ayah: 7, display: '2:7' },
    ayahB: { surah: 2, ayah: 18, display: '2:18' },
    confusionReason: {
      en: 'Both describe the state of disbelievers with parallel structure near the start of Al-Baqara.',
      ar: 'كلاهما يصف حال الكافرين ببنية متوازية في بداية البقرة.',
    },
    keyDifference: {
      en: 'Ayah 7 mentions sealed hearts, eyes, and ears; Ayah 18 uses the parable of the deaf and blind.',
      ar: 'الآية 7 تذكر ختم القلوب والأبصار والأسماع؛ الآية 18 تستخدم مثل الصُّمِّ والبُكْمِ.',
    },
    memorizerTip: {
      en: 'Ayah 7: "khatama" (sealed) — the word "khatama" anchors this ayah. Ayah 18: "summun bukmun" — two pairs of disability.',
      ar: 'الآية 7: "خَتَمَ" — كلمة "ختم" هي المرساة. الآية 18: "صُمٌّ بُكْمٌ" — زوجان من الآفات.',
    },
    riskLevel: 'high',
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
  {
    id: 'cp_hud_50_vs_araf_65',
    ayahA: { surah: 7, ayah: 65, display: '7:65' },
    ayahB: { surah: 11, ayah: 50, display: '11:50' },
    confusionReason: {
      en: 'Both introduce Prophet Hud addressing the people of Aad with nearly identical wording.',
      ar: 'كلاهما يقدم النبي هود مخاطباً قوم عاد بصياغة شبه متطابقة.',
    },
    keyDifference: {
      en: 'The surrounding context differs: Surah 7 places it after Salih; Surah 11 follows the story of Nuh.',
      ar: 'السياق المحيط مختلف: في سورة 7 يأتي بعد صالح؛ في سورة 11 يأتي بعد قصة نوح.',
    },
    memorizerTip: {
      en: 'Anchor Surah 7 to "after Salih" order; anchor Surah 11 to "after Nuh" order.',
      ar: 'ربط سورة 7 بـ"بعد صالح"؛ وربط سورة 11 بـ"بعد نوح".',
    },
    riskLevel: 'high',
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
  {
    id: 'cp_musa_introoduction_20_vs_28',
    ayahA: { surah: 20, ayah: 9, rangeEnd: 16, display: '20:9-16' },
    ayahB: { surah: 28, ayah: 29, rangeEnd: 35, display: '28:29-35' },
    confusionReason: {
      en: 'Both narrate Prophet Musa seeing fire and approaching it, with similar vocabulary.',
      ar: 'كلاهما يروي النبي موسى يرى ناراً ويقترب منها بمفردات متشابهة.',
    },
    keyDifference: {
      en: 'Surah 20 uses "Tur Sina"; Surah 28 uses "the right side of the mount". The divine address differs in wording.',
      ar: 'سورة 20 تذكر "طُورَ سَيْنَاء"؛ سورة 28 تذكر "جانب الطُّور الأيمن". صياغة الخطاب الإلهي تختلف.',
    },
    memorizerTip: {
      en: 'Surah 20 (Ta-Ha): "innani ana rabbuka" — the direct divine proclamation is distinct. Surah 28: longer build-up before the address.',
      ar: 'سورة 20 (طه): "إِنَّنِي أَنَا رَبُّكَ" — الإعلان الإلهي المباشر مميز. سورة 28: التمهيد أطول قبل الخطاب.',
    },
    riskLevel: 'high',
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
  {
    id: 'cp_ibrahim_dua_14_vs_2',
    ayahA: { surah: 2, ayah: 127, rangeEnd: 129, display: '2:127-129' },
    ayahB: { surah: 14, ayah: 35, rangeEnd: 41, display: '14:35-41' },
    confusionReason: {
      en: 'Both contain prayers of Prophet Ibrahim for his progeny in Makkah, with overlapping themes.',
      ar: 'كلاهما يتضمن دعاء النبي إبراهيم لذريته في مكة بمضامين متداخلة.',
    },
    keyDifference: {
      en: 'Al-Baqara prayer is for the Muslim community and raising the Kaaba; Surah Ibrahim focuses on the land, idols, and future generations.',
      ar: 'دعاء البقرة للأمة الإسلامية ورفع الكعبة؛ سورة إبراهيم يركز على البلد والأصنام والذرية.',
    },
    memorizerTip: {
      en: 'Anchor: Al-Baqara contains the Kaaba-building narrative just before. Surah Ibrahim: the surah is named after Ibrahim.',
      ar: 'المرساة: البقرة تحتوي رواية بناء الكعبة قبلها مباشرة. سورة إبراهيم: السورة مسماة باسم إبراهيم.',
    },
    riskLevel: 'medium',
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
  {
    id: 'cp_nuh_7_vs_hud_11',
    ayahA: { surah: 7, ayah: 59, rangeEnd: 64, display: '7:59-64' },
    ayahB: { surah: 11, ayah: 25, rangeEnd: 49, display: '11:25-49' },
    confusionReason: {
      en: 'Both tell the story of Prophet Nuh with similar narrative structure and his call to his people.',
      ar: 'كلاهما يحكي قصة النبي نوح ببنية سردية متشابهة ودعوته لقومه.',
    },
    keyDifference: {
      en: 'Surah 7 is a brief summary. Surah 11 is the most detailed account of Nuh, including the dialogue with his son.',
      ar: 'سورة 7 ملخص موجز. سورة 11 هي الرواية الأكثر تفصيلاً لنوح، شاملة الحوار مع ابنه.',
    },
    memorizerTip: {
      en: "Surah 11 (Hud): the son's drowning episode is unique to Surah 11. That detail anchors it.",
      ar: 'سورة 11 (هود): غرق الابن فريد في سورة هود. هذه التفصيلة هي المرساة.',
    },
    riskLevel: 'medium',
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
];

// ---------------------------------------------------------------------------
// Memorization Links — structural similarities across surahs
// ---------------------------------------------------------------------------

export const MEMORIZATION_LINKS: MemorizationLink[] = [
  {
    id: 'ml_fatiha_vs_baqara_opening',
    sourceAyah: { surah: 1, ayah: 1, rangeEnd: 7, display: '1:1-7' },
    targetAyah: { surah: 2, ayah: 1, rangeEnd: 5, display: '2:1-5' },
    sourceSurah: 1,
    targetSurah: 2,
    linkType: 'chronological_story_sequence',
    similarityReason: {
      en: 'Al-Fatiha asks for guidance to the straight path; Al-Baqara opens with "this is the Book, no doubt, a guidance for those who fear Allah."',
      ar: 'الفاتحة تطلب الهداية إلى الصراط المستقيم؛ البقرة تفتح بـ"ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ".',
    },
    memorizerHint: {
      en: 'Al-Fatiha ends with asking for guidance; Al-Baqara opens by announcing the guidance. They are thematically paired.',
      ar: 'الفاتحة تختتم بطلب الهداية؛ البقرة تفتتح بالإعلان عن الهداية. هما مقترنتان موضوعياً.',
    },
    differenceNote: {
      en: 'Al-Fatiha is a supplication; Al-Baqara is a declaration.',
      ar: 'الفاتحة دعاء؛ البقرة إعلان.',
    },
    riskOfConfusion: 'low',
    evidenceRefs: [],
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
  {
    id: 'ml_yunus_vs_hud_prophet_stories',
    sourceAyah: { surah: 10, ayah: 71, rangeEnd: 73, display: '10:71-73' },
    targetAyah: { surah: 11, ayah: 25, rangeEnd: 49, display: '11:25-49' },
    sourceSurah: 10,
    targetSurah: 11,
    linkType: 'repeated_story',
    similarityReason: {
      en: 'Both Surah Yunus and Surah Hud contain a concentrated sequence of prophet stories (Nuh, Hud, Salih, Ibrahim, Lut, Shuayb, Musa).',
      ar: 'كل من سورة يونس وسورة هود تحتوي تسلسلاً مركزاً من قصص الأنبياء.',
    },
    memorizerHint: {
      en: 'Surahs 10 and 11 are "twins" — both cover the same prophet sequence but Surah 11 is more detailed.',
      ar: 'السورتان 10 و11 "توأمان" — كلاهما يغطي نفس تسلسل الأنبياء لكن سورة 11 أكثر تفصيلاً.',
    },
    differenceNote: {
      en: 'Surah Yunus emphasizes faith and repentance (Yunus\'s people believed); Surah Hud emphasizes steadfastness amid punishment.',
      ar: 'سورة يونس تؤكد الإيمان والتوبة (قوم يونس آمنوا)؛ سورة هود تؤكد الثبات في مواجهة العذاب.',
    },
    riskOfConfusion: 'high',
    evidenceRefs: [],
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
  {
    id: 'ml_kahf_opening_vs_kahf_ending',
    sourceAyah: { surah: 18, ayah: 1, rangeEnd: 8, display: '18:1-8' },
    targetAyah: { surah: 18, ayah: 102, rangeEnd: 110, display: '18:102-110' },
    sourceSurah: 18,
    targetSurah: 18,
    linkType: 'similar_opening',
    similarityReason: {
      en: 'Al-Kahf opens praising Allah for the Book and warning about companions of evil; it closes with the reality of deeds and meeting Allah.',
      ar: 'الكهف تفتح بحمد الله على الكتاب والتحذير من قرين السوء؛ وتختتم بحقيقة الأعمال ولقاء الله.',
    },
    memorizerHint: {
      en: 'The opening sets up the theme of test and trial; the closing resolves it with accountability. Reading both together reinforces the surah\'s arc.',
      ar: 'المقدمة تؤسس موضوع الابتلاء؛ الخاتمة تحله بالمحاسبة. قراءتهما معاً تعزز قوس السورة.',
    },
    differenceNote: {
      en: 'Opening is about revelation and its purpose; closing is about personal accountability on the Day of Judgement.',
      ar: 'البداية عن الوحي وغرضه؛ الختام عن المحاسبة الشخصية يوم القيامة.',
    },
    riskOfConfusion: 'low',
    evidenceRefs: [],
    autoGenerated: true,
    reviewStatus: 'needs_review',
    humanReviewRequired: true,
  },
];

// ---------------------------------------------------------------------------
// Repeated Phrases — phrases that recur multiple times in the Quran
// ---------------------------------------------------------------------------

export const REPEATED_PHRASES: QuranRepeatedPhrase[] = [
  {
    id: 'rp_fabiayyi_ala',
    phraseArabic: 'فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ',
    transliteration: "Fabiy'ayyi alaa'i rabbikuma tukadhdhibaan",
    meaningEn: 'Then which of the favors of your Lord will you deny?',
    meaningAr: 'فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ',
    occurrences: [
      { surah: 55, ayah: 13, display: '55:13' },
      { surah: 55, ayah: 16, display: '55:16' },
      { surah: 55, ayah: 18, display: '55:18' },
      { surah: 55, ayah: 21, display: '55:21' },
      { surah: 55, ayah: 23, display: '55:23' },
      { surah: 55, ayah: 25, display: '55:25' },
      { surah: 55, ayah: 28, display: '55:28' },
      { surah: 55, ayah: 30, display: '55:30' },
      { surah: 55, ayah: 32, display: '55:32' },
      { surah: 55, ayah: 34, display: '55:34' },
      { surah: 55, ayah: 36, display: '55:36' },
      { surah: 55, ayah: 38, display: '55:38' },
      { surah: 55, ayah: 40, display: '55:40' },
      { surah: 55, ayah: 42, display: '55:42' },
      { surah: 55, ayah: 45, display: '55:45' },
      { surah: 55, ayah: 47, display: '55:47' },
      { surah: 55, ayah: 49, display: '55:49' },
      { surah: 55, ayah: 51, display: '55:51' },
      { surah: 55, ayah: 53, display: '55:53' },
      { surah: 55, ayah: 55, display: '55:55' },
      { surah: 55, ayah: 57, display: '55:57' },
      { surah: 55, ayah: 59, display: '55:59' },
      { surah: 55, ayah: 61, display: '55:61' },
      { surah: 55, ayah: 63, display: '55:63' },
      { surah: 55, ayah: 65, display: '55:65' },
      { surah: 55, ayah: 67, display: '55:67' },
      { surah: 55, ayah: 69, display: '55:69' },
      { surah: 55, ayah: 71, display: '55:71' },
      { surah: 55, ayah: 73, display: '55:73' },
      { surah: 55, ayah: 75, display: '55:75' },
      { surah: 55, ayah: 77, display: '55:77' },
    ],
    themeLabel: {
      en: 'Divine Gratitude Refrain',
      ar: 'لازمة شكر الله',
    },
    memorizerNote: {
      en: 'This phrase repeats 31 times in Surah Ar-Rahman — once memorized, it becomes a rhythm anchor for the entire surah.',
      ar: 'هذه العبارة تتكرر 31 مرة في سورة الرحمن — بمجرد حفظها تصبح مرساة إيقاعية لكامل السورة.',
    },
    autoGenerated: true,
    reviewStatus: 'needs_review',
  },
  {
    id: 'rp_waylun_yawmaidhin',
    phraseArabic: 'وَيْلٌ يَوْمَئِذٍ لِّلْمُكَذِّبِينَ',
    transliteration: 'Waylun yawma-idhin lil-mukadhdhibeen',
    meaningEn: 'Woe that Day to the deniers!',
    meaningAr: 'الويل يوم القيامة للمكذبين',
    occurrences: [
      { surah: 77, ayah: 15, display: '77:15' },
      { surah: 77, ayah: 19, display: '77:19' },
      { surah: 77, ayah: 24, display: '77:24' },
      { surah: 77, ayah: 28, display: '77:28' },
      { surah: 77, ayah: 34, display: '77:34' },
      { surah: 77, ayah: 37, display: '77:37' },
      { surah: 77, ayah: 40, display: '77:40' },
      { surah: 77, ayah: 45, display: '77:45' },
      { surah: 77, ayah: 47, display: '77:47' },
      { surah: 77, ayah: 49, display: '77:49' },
    ],
    themeLabel: {
      en: 'Warning Refrain',
      ar: 'لازمة التحذير',
    },
    memorizerNote: {
      en: 'This refrain divides Surah Al-Mursalat into sections — each repetition marks a new argument about the Day of Judgement.',
      ar: 'هذه اللازمة تقسم سورة المرسلات إلى أقسام — كل تكرار يعلم بحجة جديدة عن يوم القيامة.',
    },
    autoGenerated: true,
    reviewStatus: 'needs_review',
  },
  {
    id: 'rp_innahu_huwal_azizul_hakim',
    phraseArabic: 'إِنَّهُ هُوَ الْعَزِيزُ الْحَكِيمُ',
    transliteration: 'Innahu huwal-azizul-hakim',
    meaningEn: 'Indeed, He is the Exalted in Might, the Wise.',
    meaningAr: 'إنه هو العزيز الحكيم',
    occurrences: [
      { surah: 2, ayah: 129, display: '2:129' },
      { surah: 3, ayah: 6, display: '3:6' },
      { surah: 3, ayah: 18, display: '3:18' },
      { surah: 6, ayah: 96, display: '6:96' },
      { surah: 9, ayah: 40, display: '9:40' },
      { surah: 14, ayah: 4, display: '14:4' },
      { surah: 27, ayah: 9, display: '27:9' },
      { surah: 31, ayah: 9, display: '31:9' },
      { surah: 39, ayah: 1, display: '39:1' },
      { surah: 45, ayah: 2, display: '45:2' },
      { surah: 46, ayah: 2, display: '46:2' },
    ],
    themeLabel: {
      en: 'Divine Attribute: Might and Wisdom',
      ar: 'صفة إلهية: العزة والحكمة',
    },
    memorizerNote: {
      en: 'When you encounter "al-Aziz al-Hakim" as an ending formula, recognize it as a common Quranic closing for passages about divine decree.',
      ar: 'عند مصادفة "العزيز الحكيم" كصيغة ختامية، اعرف أنها خاتمة قرآنية شائعة لمقاطع القدر الإلهي.',
    },
    autoGenerated: true,
    reviewStatus: 'needs_review',
  },
];

// ---------------------------------------------------------------------------
// Story Recurrences — where each story appears across the Quran
// ---------------------------------------------------------------------------

export const STORY_RECURRENCES: StoryRecurrenceEntry[] = [
  {
    storyId: 'story_musa',
    titleEn: 'Story of Prophet Musa (Moses)',
    titleAr: 'قصة النبي موسى عليه السلام',
    surahOccurrences: [
      { surahNumber: 2, surahName: 'Al-Baqara', ayahRange: { surah: 2, ayah: 49, rangeEnd: 73, display: '2:49-73' }, coverageNote: { en: 'Detailed account of Bani Israel deliverance', ar: 'رواية مفصلة لإنقاذ بني إسرائيل' } },
      { surahNumber: 7, surahName: 'Al-Araf', ayahRange: { surah: 7, ayah: 103, rangeEnd: 162, display: '7:103-162' }, coverageNote: { en: 'Full confrontation with Pharaoh and Bani Israel', ar: 'المواجهة الكاملة مع فرعون وبني إسرائيل' } },
      { surahNumber: 10, surahName: 'Yunus', ayahRange: { surah: 10, ayah: 75, rangeEnd: 92, display: '10:75-92' }, coverageNote: { en: 'Confrontation with Pharaoh and his fate', ar: 'المواجهة مع فرعون ومصيره' } },
      { surahNumber: 11, surahName: 'Hud', ayahRange: { surah: 11, ayah: 96, rangeEnd: 99, display: '11:96-99' }, coverageNote: { en: 'Brief mention in series of prophets', ar: 'ذكر موجز في سلسلة الأنبياء' } },
      { surahNumber: 14, surahName: 'Ibrahim', ayahRange: { surah: 14, ayah: 5, rangeEnd: 8, display: '14:5-8' }, coverageNote: { en: 'Musa reminding Bani Israel of blessings', ar: 'موسى يذكّر بني إسرائيل بالنعم' } },
      { surahNumber: 17, surahName: 'Al-Isra', ayahRange: { surah: 17, ayah: 101, rangeEnd: 103, display: '17:101-103' }, coverageNote: { en: 'The nine signs given to Musa', ar: 'الآيات التسع الممنوحة لموسى' } },
      { surahNumber: 18, surahName: 'Al-Kahf', ayahRange: { surah: 18, ayah: 60, rangeEnd: 82, display: '18:60-82' }, coverageNote: { en: 'Musa and Khidr journey', ar: 'رحلة موسى والخضر' } },
      { surahNumber: 19, surahName: 'Maryam', ayahRange: { surah: 19, ayah: 51, rangeEnd: 53, display: '19:51-53' }, coverageNote: { en: 'Brief praise of Musa', ar: 'ثناء موجز على موسى' } },
      { surahNumber: 20, surahName: 'Ta-Ha', ayahRange: { surah: 20, ayah: 9, rangeEnd: 98, display: '20:9-98' }, coverageNote: { en: 'Most detailed account of Musa\'s prophethood', ar: 'أكثر الروايات تفصيلاً لنبوة موسى' } },
      { surahNumber: 26, surahName: 'Ash-Shuara', ayahRange: { surah: 26, ayah: 10, rangeEnd: 68, display: '26:10-68' }, coverageNote: { en: 'Dialogue with Pharaoh and the magicians', ar: 'حوار مع فرعون والسحرة' } },
      { surahNumber: 27, surahName: 'An-Naml', ayahRange: { surah: 27, ayah: 7, rangeEnd: 14, display: '27:7-14' }, coverageNote: { en: 'The fire and the staff', ar: 'النار والعصا' } },
      { surahNumber: 28, surahName: 'Al-Qasas', ayahRange: { surah: 28, ayah: 1, rangeEnd: 43, display: '28:1-43' }, coverageNote: { en: 'Birth, upbringing, and early mission of Musa', ar: 'ولادة موسى ونشأته ومهمته الأولى' } },
      { surahNumber: 40, surahName: 'Ghafir', ayahRange: { surah: 40, ayah: 23, rangeEnd: 46, display: '40:23-46' }, coverageNote: { en: 'The believer of Pharaoh\'s household', ar: 'مؤمن آل فرعون' } },
      { surahNumber: 43, surahName: 'Az-Zukhruf', ayahRange: { surah: 43, ayah: 46, rangeEnd: 56, display: '43:46-56' }, coverageNote: { en: 'Musa\'s signs before Pharaoh', ar: 'آيات موسى أمام فرعون' } },
      { surahNumber: 44, surahName: 'Ad-Dukhan', ayahRange: { surah: 44, ayah: 17, rangeEnd: 33, display: '44:17-33' }, coverageNote: { en: 'Trial of Pharaoh\'s people', ar: 'ابتلاء قوم فرعون' } },
      { surahNumber: 51, surahName: 'Adh-Dhariyat', ayahRange: { surah: 51, ayah: 38, rangeEnd: 40, display: '51:38-40' }, coverageNote: { en: 'Brief mention as a warning example', ar: 'ذكر موجز كمثال تحذيري' } },
      { surahNumber: 54, surahName: 'Al-Qamar', ayahRange: { surah: 54, ayah: 41, rangeEnd: 42, display: '54:41-42' }, coverageNote: { en: 'Very brief mention', ar: 'ذكر موجز جداً' } },
      { surahNumber: 66, surahName: 'At-Tahrim', ayahRange: { surah: 66, ayah: 11, display: '66:11' }, coverageNote: { en: 'Asiya, wife of Pharaoh, cited as example', ar: 'آسيا زوجة فرعون مضروبة كمثل' } },
      { surahNumber: 73, surahName: 'Al-Muzzammil', ayahRange: { surah: 73, ayah: 15, rangeEnd: 16, display: '73:15-16' }, coverageNote: { en: 'Musa mentioned as a parallel messenger', ar: 'موسى مذكور كرسول موازٍ' } },
      { surahNumber: 79, surahName: 'An-Naziat', ayahRange: { surah: 79, ayah: 15, rangeEnd: 26, display: '79:15-26' }, coverageNote: { en: 'Pharaoh\'s arrogance and punishment', ar: 'تكبر فرعون وعذابه' } },
    ],
    dominantSurahNumber: 20,
    totalOccurrences: 20,
    reviewStatus: 'needs_review',
  },
  {
    storyId: 'story_ibrahim',
    titleEn: 'Story of Prophet Ibrahim (Abraham)',
    titleAr: 'قصة النبي إبراهيم عليه السلام',
    surahOccurrences: [
      { surahNumber: 2, surahName: 'Al-Baqara', ayahRange: { surah: 2, ayah: 124, rangeEnd: 141, display: '2:124-141' }, coverageNote: { en: 'Building the Kaaba, prayers for progeny', ar: 'بناء الكعبة، الدعاء للذرية' } },
      { surahNumber: 3, surahName: 'Aal-Imran', ayahRange: { surah: 3, ayah: 65, rangeEnd: 68, display: '3:65-68' }, coverageNote: { en: 'Ibrahim as neither Jew nor Christian', ar: 'إبراهيم لم يكن يهودياً ولا نصرانياً' } },
      { surahNumber: 6, surahName: 'Al-An\'am', ayahRange: { surah: 6, ayah: 74, rangeEnd: 84, display: '6:74-84' }, coverageNote: { en: 'Ibrahim\'s search for truth through stars, moon, sun', ar: 'بحث إبراهيم عن الحق عبر النجوم والقمر والشمس' } },
      { surahNumber: 9, surahName: 'At-Tawba', ayahRange: { surah: 9, ayah: 113, rangeEnd: 114, display: '9:113-114' }, coverageNote: { en: 'Ibrahim\'s distancing from his father', ar: 'تبري إبراهيم من أبيه' } },
      { surahNumber: 11, surahName: 'Hud', ayahRange: { surah: 11, ayah: 69, rangeEnd: 83, display: '11:69-83' }, coverageNote: { en: 'Angels visit Ibrahim; Lut\'s people destroyed', ar: 'زيارة الملائكة لإبراهيم؛ هلاك قوم لوط' } },
      { surahNumber: 14, surahName: 'Ibrahim', ayahRange: { surah: 14, ayah: 35, rangeEnd: 41, display: '14:35-41' }, coverageNote: { en: 'Ibrahim\'s prayer for Makkah', ar: 'دعاء إبراهيم لمكة' } },
      { surahNumber: 15, surahName: 'Al-Hijr', ayahRange: { surah: 15, ayah: 51, rangeEnd: 60, display: '15:51-60' }, coverageNote: { en: 'Angels visit Ibrahim', ar: 'زيارة الملائكة لإبراهيم' } },
      { surahNumber: 16, surahName: 'An-Nahl', ayahRange: { surah: 16, ayah: 120, rangeEnd: 123, display: '16:120-123' }, coverageNote: { en: 'Ibrahim as an umma', ar: 'إبراهيم كأمة' } },
      { surahNumber: 19, surahName: 'Maryam', ayahRange: { surah: 19, ayah: 41, rangeEnd: 50, display: '19:41-50' }, coverageNote: { en: 'Ibrahim\'s dialogue with his father', ar: 'حوار إبراهيم مع أبيه' } },
      { surahNumber: 21, surahName: 'Al-Anbiya', ayahRange: { surah: 21, ayah: 51, rangeEnd: 73, display: '21:51-73' }, coverageNote: { en: 'Ibrahim smashing idols; fire miracle', ar: 'إبراهيم يحطم الأصنام؛ معجزة النار' } },
      { surahNumber: 22, surahName: 'Al-Hajj', ayahRange: { surah: 22, ayah: 26, rangeEnd: 27, display: '22:26-27' }, coverageNote: { en: 'Ibrahim called to declare Hajj', ar: 'إبراهيم مأمور بإعلان الحج' } },
      { surahNumber: 26, surahName: 'Ash-Shuara', ayahRange: { surah: 26, ayah: 69, rangeEnd: 89, display: '26:69-89' }, coverageNote: { en: 'Ibrahim\'s dialogue with his people', ar: 'حوار إبراهيم مع قومه' } },
      { surahNumber: 29, surahName: 'Al-Ankabut', ayahRange: { surah: 29, ayah: 16, rangeEnd: 27, display: '29:16-27' }, coverageNote: { en: 'Ibrahim and the fire', ar: 'إبراهيم والنار' } },
      { surahNumber: 37, surahName: 'As-Saffat', ayahRange: { surah: 37, ayah: 83, rangeEnd: 113, display: '37:83-113' }, coverageNote: { en: 'Ibrahim\'s dream sacrifice of Ismail', ar: 'رؤيا إبراهيم بذبح إسماعيل' } },
      { surahNumber: 43, surahName: 'Az-Zukhruf', ayahRange: { surah: 43, ayah: 26, rangeEnd: 28, display: '43:26-28' }, coverageNote: { en: 'Ibrahim\'s rejection of his people', ar: 'تبري إبراهيم من قومه' } },
      { surahNumber: 51, surahName: 'Adh-Dhariyat', ayahRange: { surah: 51, ayah: 24, rangeEnd: 34, display: '51:24-34' }, coverageNote: { en: 'Angels visit Ibrahim', ar: 'زيارة الملائكة لإبراهيم' } },
      { surahNumber: 60, surahName: 'Al-Mumtahana', ayahRange: { surah: 60, ayah: 4, rangeEnd: 6, display: '60:4-6' }, coverageNote: { en: 'Ibrahim as a good example in distancing from disbelievers', ar: 'إبراهيم كأسوة حسنة في التبري من الكافرين' } },
    ],
    dominantSurahNumber: 14,
    totalOccurrences: 17,
    reviewStatus: 'needs_review',
  },
];

// ---------------------------------------------------------------------------
// Memorization Intelligence Collection
// ---------------------------------------------------------------------------

export const MEMORIZATION_INTELLIGENCE: MemorizationIntelligence = {
  version: '1.0.0',
  generatedAt: '2026-06-06',
  links: MEMORIZATION_LINKS,
  confusionPairs: CONFUSION_PAIRS,
  repeatedPhrases: REPEATED_PHRASES,
  storyRecurrences: STORY_RECURRENCES,
  surahConnections: [],
  reviewNote: {
    en: 'All memorization intelligence data is auto-generated and requires scholarly review before production use.',
    ar: 'جميع بيانات ذكاء الحفظ مولّدة تلقائياً وتستلزم مراجعة علمية قبل الاستخدام الإنتاجي.',
  },
};

export function getConfusionPairsForSurah(surahNumber: number): ConfusionPair[] {
  return CONFUSION_PAIRS.filter(
    (p) => p.ayahA.surah === surahNumber || p.ayahB.surah === surahNumber,
  );
}

export function getMemorizationLinksForSurah(surahNumber: number): MemorizationLink[] {
  return MEMORIZATION_LINKS.filter(
    (l) => l.sourceSurah === surahNumber || l.targetSurah === surahNumber,
  );
}

export function getStoryRecurrence(storyId: string): StoryRecurrenceEntry | undefined {
  return STORY_RECURRENCES.find((r) => r.storyId === storyId);
}
