/**
 * Phase H — Quranic Vocabulary / Gharib Al-Quran (live QAC data)
 *
 * Full vocabulary lookup backed by the Quranic Arabic Corpus (QAC).
 * Shows root, morphological pattern, POS, English gloss, Arabic meaning,
 * and source attribution for every looked-up word.
 *
 * Per policy: word meanings must NEVER be generated by AI alone.
 */
import { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Search,
  BookOpen,
  AlertCircle,
  Clock,
  BookMarked,
  Globe,
  FlaskConical,
  Info,
  ArrowRight,
  CheckCircle,
} from 'lucide-react';
import { useLanguageStore } from '../../stores/languageStore';
import { t } from '../../i18n/translations';
import { vocabularyApi, VocabularyResponse } from '../../lib/api';
import clsx from 'clsx';

// ---------------------------------------------------------------------------
// Scholarly source catalogue — rich display data for planned lexicons
// ---------------------------------------------------------------------------

interface LexiconEntry {
  id: string;
  titleAr: string;
  titleEn: string;
  authorAr: string;
  authorEn: string;
  eraAr: string;
  eraEn: string;
  focusAr: string;
  focusEn: string;
  volumes?: string;
  category: 'arabic' | 'english' | 'digital';
}

const CLASSICAL_ARABIC_SOURCES: LexiconEntry[] = [
  {
    id: 'gharib_al_quran_ibn_qutaybah',
    titleAr: 'غريب القرآن',
    titleEn: "Gharib Al-Quran (Ibn Qutayba)",
    authorAr: 'ابن قتيبة الدينوري',
    authorEn: 'Ibn Qutayba al-Dinawari',
    eraAr: 'القرن الثالث الهجري (ت. 276 هـ)',
    eraEn: '3rd century AH  ·  d. 276 AH / 889 CE',
    focusAr: 'أقدم مصدر متخصص في شرح الكلمات القرآنية النادرة',
    focusEn: 'Earliest specialized work on rare and unusual Quranic vocabulary',
    category: 'arabic',
  },
  {
    id: 'mufradat_al_raghib',
    titleAr: 'مفردات ألفاظ القرآن',
    titleEn: 'Mufradat Al-Raghib Al-Isfahani',
    authorAr: 'الراغب الأصفهاني',
    authorEn: 'Al-Raghib Al-Isfahani',
    eraAr: 'القرن الخامس الهجري (ت. 502 هـ)',
    eraEn: '5th century AH  ·  d. 502 AH / 1108 CE',
    focusAr: 'الأكثر توثيقاً في مصطلحات القرآن وألفاظه المتخصصة — مرجع أمهات التفاسير',
    focusEn: 'The most cited specialized Quranic terminology lexicon — referenced by all major tafsir scholars',
    category: 'arabic',
  },
  {
    id: 'lisan_al_arab',
    titleAr: 'لسان العرب',
    titleEn: 'Lisan Al-Arab (Ibn Manzur)',
    authorAr: 'ابن منظور',
    authorEn: 'Ibn Manzur',
    eraAr: 'القرن السابع الهجري (ت. 711 هـ)',
    eraEn: '7th century AH  ·  d. 711 AH / 1311 CE',
    focusAr: 'أضخم المعاجم العربية الكلاسيكية — يضمّ شواهد قرآنية وأدبية موسّعة',
    focusEn: 'The largest classical Arabic dictionary — extensive Quranic and literary citations',
    volumes: '20',
    category: 'arabic',
  },
  {
    id: 'qamus_al_muhit',
    titleAr: 'القاموس المحيط',
    titleEn: 'Al-Qamus Al-Muhit (Al-Fayruzabadi)',
    authorAr: 'الفيروزآبادي',
    authorEn: 'Al-Fayruzabadi',
    eraAr: 'القرن التاسع الهجري (ت. 817 هـ)',
    eraEn: '9th century AH  ·  d. 817 AH / 1414 CE',
    focusAr: 'معجم شامل أساسي في الدراسات اللغوية العربية',
    focusEn: 'Comprehensive classical Arabic lexicon — authoritative Sunni linguistic reference',
    category: 'arabic',
  },
  {
    id: 'al_nihaya_ibn_al_athir',
    titleAr: 'النهاية في غريب الحديث والأثر',
    titleEn: 'Al-Nihaya (Ibn Al-Athir)',
    authorAr: 'ابن الأثير الجزري',
    authorEn: "Ibn Al-Athir al-Jazari",
    eraAr: 'القرن السادس الهجري (ت. 606 هـ)',
    eraEn: '6th century AH  ·  d. 606 AH / 1209 CE',
    focusAr: 'الكلمات الغريبة في الحديث النبوي والقرآن الكريم',
    focusEn: 'Rare and unusual words in Hadith narrations and the Quran',
    category: 'arabic',
  },
];

const ENGLISH_DIGITAL_SOURCES: LexiconEntry[] = [
  {
    id: 'lanes_lexicon',
    titleAr: 'معجم لين العربي الإنجليزي',
    titleEn: "Lane's Arabic-English Lexicon",
    authorAr: 'إدوارد وليام لين',
    authorEn: 'Edward William Lane',
    eraAr: 'القرن التاسع عشر الميلادي (ت. 1876 م)',
    eraEn: '19th century CE  ·  d. 1876',
    focusAr: 'المعجم العربي الإنجليزي الأشمل — مستند بالكامل إلى لسان العرب والمصادر الكلاسيكية',
    focusEn: 'Most comprehensive Arabic-English lexicon — fully grounded in classical sources',
    volumes: '8',
    category: 'english',
  },
  {
    id: 'quranic_arabic_corpus',
    titleAr: 'مدوّنة القرآن العربية',
    titleEn: 'Quranic Arabic Corpus',
    authorAr: 'قيس دوكس — جامعة ليدز',
    authorEn: 'Kais Dukes, University of Leeds',
    eraAr: 'حديث (2009–2011)',
    eraEn: 'Modern  ·  2009–2011',
    focusAr: 'التحليل الصرفي والنحوي لكل كلمة قرآنية — 77,430 كلمة مُعرَبة بالكامل',
    focusEn: 'Word-by-word morphological and syntactic annotation of all 77,430 Quranic words',
    category: 'digital',
  },
];

const EXAMPLE_WORDS = ['صمد', 'رحمة', 'تقوى', 'نور', 'صبر', 'حكمة', 'إخلاص', 'توكّل'];

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

export function VocabularyPage() {
  const { language } = useLanguageStore();
  const isRtl = language === 'ar';

  const [query, setQuery] = useState('');
  const [result, setResult] = useState<VocabularyResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSearch(e: React.FormEvent) {
    e.preventDefault();
    const word = query.trim();
    if (!word) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await vocabularyApi.lookup(word);
      setResult(res.data);
    } catch {
      setError(language === 'ar' ? 'حدث خطأ. حاول مجدداً.' : 'An error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8" dir={isRtl ? 'rtl' : 'ltr'}>

      {/* Header */}
      <div className="mb-6 text-center">
        <div className="flex items-center justify-center gap-3 mb-4">
          <div className="p-3 bg-teal-50 rounded-xl border border-teal-100">
            <BookOpen className="w-8 h-8 text-teal-600" />
          </div>
        </div>
        <h1 className={clsx('text-3xl font-bold text-gray-900 mb-2', isRtl && 'font-arabic')}>
          {t('vocab_page_title', language)}
        </h1>
        <p className={clsx('text-gray-500 max-w-xl mx-auto text-base', isRtl && 'font-arabic')}>
          {t('vocab_page_subtitle', language)}
        </p>
      </div>

      {/* About Gharib Al-Quran */}
      <div className={clsx(
        'rounded-xl border border-teal-100 bg-teal-50/60 px-5 py-4 mb-6 flex gap-3',
        isRtl && 'flex-row-reverse'
      )}>
        <Info className="w-5 h-5 text-teal-600 shrink-0 mt-0.5" />
        <p className={clsx('text-sm text-teal-800 leading-relaxed', isRtl && 'text-right font-arabic')}
           dir={isRtl ? 'rtl' : 'ltr'}>
          {t('vocab_about_gharib', language)}
        </p>
      </div>

      {/* Search form */}
      <form onSubmit={handleSearch} className="mb-4">
        <div className="flex gap-3">
          <div className="relative flex-1">
            <Search className={clsx(
              'absolute top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400 pointer-events-none',
              isRtl ? 'right-3' : 'left-3'
            )} />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={t('vocab_search_placeholder', language)}
              className={clsx(
                'w-full border border-gray-300 rounded-lg py-3 text-base shadow-sm',
                'focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-teal-500',
                isRtl ? 'pr-10 pl-4 text-right font-arabic' : 'pl-10 pr-4'
              )}
              dir={isRtl ? 'rtl' : 'ltr'}
            />
          </div>
          <button
            type="submit"
            disabled={loading || !query.trim()}
            className={clsx(
              'px-6 py-3 bg-teal-600 text-white rounded-lg font-medium shadow-sm',
              'hover:bg-teal-700 active:bg-teal-800 transition-colors',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              isRtl && 'font-arabic'
            )}
          >
            {loading ? '...' : t('vocab_search_button', language)}
          </button>
        </div>
      </form>

      {/* Example word chips */}
      {!result && !loading && (
        <div className={clsx('mb-8 flex flex-wrap gap-2 items-center', isRtl && 'flex-row-reverse')}>
          <span className={clsx('text-xs text-gray-400 font-medium shrink-0', isRtl && 'font-arabic')}>
            {t('vocab_try_examples', language)}
          </span>
          {EXAMPLE_WORDS.map((word) => (
            <button
              key={word}
              type="button"
              onClick={() => setQuery(word)}
              className="px-3 py-1 text-sm font-arabic bg-gray-100 hover:bg-teal-50 hover:text-teal-700 border border-gray-200 hover:border-teal-300 rounded-full transition-colors"
              dir="rtl"
            >
              {word}
            </button>
          ))}
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 p-4 mb-6">
          <p className={clsx('text-red-700 text-sm', isRtl && 'text-right font-arabic')}>{error}</p>
        </div>
      )}

      {/* Result: found */}
      {result && result.status === 'found' && (
        <WordResultCard result={result} language={language} isRtl={isRtl} />
      )}

      {/* Result: safe-refusal state */}
      {result && result.status === 'no_verified_source' && (
        <SafeRefusalCard result={result} language={language} isRtl={isRtl} />
      )}

      {/* Default state — planned sources catalogue */}
      {!result && !error && !loading && (
        <PlannedSourcesCatalogue language={language} isRtl={isRtl} />
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Word result card — shown when status === 'found'
// ---------------------------------------------------------------------------

interface CardProps {
  language: 'ar' | 'en';
  isRtl: boolean;
}

interface WordResultCardProps extends CardProps {
  result: VocabularyResponse;
}

function WordResultCard({ result, language, isRtl }: WordResultCardProps) {
  return (
    <div className="space-y-4">
      {/* Main card */}
      <div className="rounded-xl border border-teal-200 bg-white p-5 shadow-sm">

        {/* Word + status */}
        <div className={clsx('flex items-start gap-3 mb-4', isRtl && 'flex-row-reverse')}>
          <CheckCircle className="w-5 h-5 text-teal-600 mt-0.5 shrink-0" />
          <div className="flex-1 min-w-0">
            <h2 className="flex items-center gap-2 flex-wrap">
              <span dir="rtl" className="font-arabic text-2xl font-bold text-gray-900">
                {result.word}
              </span>
              <span className="inline-flex items-center gap-1 text-xs font-medium text-teal-700 bg-teal-50 border border-teal-200 rounded-full px-2.5 py-0.5">
                <CheckCircle className="w-3 h-3" />
                {language === 'ar' ? 'تم التحقق' : 'Verified source'}
              </span>
            </h2>
          </div>
        </div>

        {/* Morphology chips */}
        {(result.root || result.pattern || result.pos_tag) && (
          <div className={clsx('flex flex-wrap gap-2 mb-4', isRtl && 'flex-row-reverse')}>
            {result.root && (
              <div className="flex flex-col items-center bg-teal-50 border border-teal-200 rounded-lg px-3 py-2">
                <span className={clsx('text-xs text-teal-500', isRtl && 'font-arabic')}>
                  {language === 'ar' ? 'الجذر' : 'Root'}
                </span>
                <span dir="rtl" className="font-arabic font-bold text-teal-800 text-base">
                  {result.root}
                </span>
              </div>
            )}
            {result.pattern && (
              <div className="flex flex-col items-center bg-indigo-50 border border-indigo-100 rounded-lg px-3 py-2">
                <span className={clsx('text-xs text-indigo-400', isRtl && 'font-arabic')}>
                  {language === 'ar' ? 'الوزن' : 'Pattern'}
                </span>
                <span dir="rtl" className="font-arabic font-bold text-indigo-700 text-base">
                  {result.pattern}
                </span>
              </div>
            )}
            {result.pos_tag && (
              <div className="flex flex-col items-center bg-amber-50 border border-amber-100 rounded-lg px-3 py-2">
                <span className={clsx('text-xs text-amber-500', isRtl && 'font-arabic')}>
                  {language === 'ar' ? 'نوع الكلمة' : 'Part of Speech'}
                </span>
                <span dir="rtl" className="font-arabic font-bold text-amber-800 text-base">
                  {result.pos_tag}
                </span>
              </div>
            )}
          </div>
        )}

        {/* English meaning */}
        {result.meaning_en && (
          <div className="mb-3">
            <p className="text-xs text-gray-400 uppercase tracking-wide mb-1" dir="ltr">
              {language === 'ar' ? 'المعنى بالإنجليزية' : 'English Meaning'}
            </p>
            <p dir="ltr" className="text-gray-800 text-base font-medium">
              {result.meaning_en}
            </p>
          </div>
        )}

        {/* Arabic meaning */}
        {result.meaning_ar && (
          <div className="mb-3">
            <p className="text-xs text-gray-400 uppercase tracking-wide mb-1" dir="ltr">
              {language === 'ar' ? 'المعنى العربي' : 'Arabic Meaning'}
            </p>
            <p dir="rtl" className="font-arabic text-gray-800 text-base font-medium text-right">
              {result.meaning_ar}
            </p>
          </div>
        )}

        {/* Example verses */}
        {result.example_verses && result.example_verses.length > 0 && (
          <div className="mb-3">
            <p className="text-xs text-gray-400 uppercase tracking-wide mb-1" dir="ltr">
              {language === 'ar' ? 'آيات' : 'Verse'}
            </p>
            <div className={clsx('flex flex-wrap gap-1.5', isRtl && 'flex-row-reverse')}>
              {result.example_verses.map((ref) => (
                <span
                  key={ref}
                  className="inline-flex items-center text-xs font-mono bg-gray-100 text-gray-600 border border-gray-200 rounded px-2 py-0.5"
                  dir="ltr"
                >
                  {ref}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Source attribution */}
        <div className="pt-3 border-t border-gray-100">
          <div className={clsx('flex items-center gap-1.5 text-xs text-gray-400', isRtl && 'flex-row-reverse')}>
            <BookOpen className="w-3.5 h-3.5 shrink-0" />
            <span dir="ltr">
              {result.source_title_en || result.source_id || 'Quranic Arabic Corpus'}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Safe refusal card
// ---------------------------------------------------------------------------

interface SafeRefusalCardProps extends CardProps {
  result: VocabularyResponse;
}

function SafeRefusalCard({ result, language, isRtl }: SafeRefusalCardProps) {
  const message = language === 'ar' ? result.message_ar : result.message_en;

  return (
    <div className="space-y-4">
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-5">
        <div className={clsx('flex items-start gap-3', isRtl && 'flex-row-reverse')}>
          <AlertCircle className="w-5 h-5 text-amber-600 mt-0.5 shrink-0" />
          <div className="flex-1 min-w-0">
            <h2 className={clsx('font-semibold text-amber-900 mb-1.5 text-base', isRtl && 'text-right font-arabic')}>
              <span dir={isRtl ? 'rtl' : 'ltr'}>{t('vocab_no_source_title', language)}</span>
              <span className="mx-2 text-amber-400">—</span>
              <span dir="rtl" className="font-arabic text-amber-800">{result.word}</span>
            </h2>
            <p className={clsx('text-amber-800 text-sm leading-relaxed', isRtl && 'text-right font-arabic')}
               dir={isRtl ? 'rtl' : 'ltr'}>
              {message}
            </p>
            <span className={clsx(
              'mt-3 inline-flex items-center gap-1.5 text-xs font-medium text-amber-700',
              'bg-amber-100 border border-amber-300 rounded-full px-3 py-1',
              isRtl && 'font-arabic'
            )}>
              <Clock className="w-3.5 h-3.5" />
              {t('vocab_planned_label', language)}
            </span>
          </div>
        </div>
      </div>

      {/* Policy note */}
      <div className={clsx(
        'rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 flex gap-2',
        isRtl && 'flex-row-reverse'
      )}>
        <BookMarked className="w-4 h-4 text-gray-400 shrink-0 mt-0.5" />
        <p className={clsx('text-xs text-gray-500 leading-relaxed', isRtl && 'text-right font-arabic')}
           dir={isRtl ? 'rtl' : 'ltr'}>
          {t('vocab_policy_note', language)}
        </p>
      </div>

      {/* Navigate to tafsir assistant */}
      <div className={clsx(
        'rounded-xl border border-blue-100 bg-blue-50 px-5 py-4 flex items-center gap-3',
        isRtl ? 'flex-row-reverse' : ''
      )}>
        <BookOpen className="w-5 h-5 text-blue-500 shrink-0" />
        <p className={clsx('text-sm text-blue-700 flex-1', isRtl && 'text-right font-arabic')}
           dir={isRtl ? 'rtl' : 'ltr'}>
          {t('vocab_refusal_try_tafsir', language)}
        </p>
        <Link
          to="/ask"
          className={clsx(
            'shrink-0 flex items-center gap-1 text-xs font-medium text-blue-600',
            'hover:text-blue-800 transition-colors',
            isRtl && 'flex-row-reverse font-arabic'
          )}
        >
          {language === 'ar' ? 'مساعد التدبر' : 'Tafsir Assistant'}
          <ArrowRight className={clsx('w-3.5 h-3.5', isRtl && 'rotate-180')} />
        </Link>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Planned sources catalogue — shown on initial load
// ---------------------------------------------------------------------------

function PlannedSourcesCatalogue({ language, isRtl }: CardProps) {
  return (
    <div className="space-y-8">
      {/* Under development banner */}
      <div className={clsx(
        'flex items-center gap-2.5 px-4 py-3 rounded-lg border border-gray-200 bg-white',
        isRtl && 'flex-row-reverse'
      )}>
        <Clock className="w-5 h-5 text-teal-600 shrink-0" />
        <span className={clsx('font-semibold text-gray-700 text-sm', isRtl && 'font-arabic')}>
          {t('vocab_planned_label', language)}
        </span>
        <span className={clsx('text-xs text-gray-400 ms-auto', isRtl && 'font-arabic')}>
          {t('vocab_planned_sources_label', language)}
        </span>
      </div>

      {/* Classical Arabic Lexicons */}
      <section>
        <SectionHeader
          icon={<BookOpen className="w-4 h-4 text-teal-600" />}
          label={t('vocab_sources_classical_ar_label', language)}
          isRtl={isRtl}
        />
        <div className="space-y-3">
          {CLASSICAL_ARABIC_SOURCES.map((src) => (
            <LexiconCard key={src.id} source={src} language={language} isRtl={isRtl} />
          ))}
        </div>
      </section>

      {/* English & Digital Lexicons */}
      <section>
        <SectionHeader
          icon={<Globe className="w-4 h-4 text-indigo-600" />}
          label={t('vocab_sources_english_digital_label', language)}
          isRtl={isRtl}
        />
        <div className="space-y-3">
          {ENGLISH_DIGITAL_SOURCES.map((src) => (
            <LexiconCard key={src.id} source={src} language={language} isRtl={isRtl} />
          ))}
        </div>
      </section>

      {/* Policy note */}
      <div className={clsx(
        'rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 flex gap-2',
        isRtl && 'flex-row-reverse'
      )}>
        <BookMarked className="w-4 h-4 text-gray-400 shrink-0 mt-0.5" />
        <p className={clsx('text-xs text-gray-500 leading-relaxed', isRtl && 'text-right font-arabic')}
           dir={isRtl ? 'rtl' : 'ltr'}>
          {t('vocab_policy_note', language)}
        </p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Section header
// ---------------------------------------------------------------------------

function SectionHeader({
  icon,
  label,
  isRtl,
}: {
  icon: React.ReactNode;
  label: string;
  isRtl: boolean;
}) {
  return (
    <div className={clsx('flex items-center gap-2 mb-3', isRtl && 'flex-row-reverse')}>
      <span className="p-1.5 bg-gray-100 rounded-lg">{icon}</span>
      <h2 className={clsx('font-semibold text-gray-700 text-sm uppercase tracking-wide', isRtl && 'font-arabic')}>
        {label}
      </h2>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Lexicon source card
// ---------------------------------------------------------------------------

function LexiconCard({
  source,
  language,
  isRtl,
}: {
  source: LexiconEntry;
  language: 'ar' | 'en';
  isRtl: boolean;
}) {
  const title = isRtl ? source.titleAr : source.titleEn;
  const author = isRtl ? source.authorAr : source.authorEn;
  const era = isRtl ? source.eraAr : source.eraEn;
  const focus = isRtl ? source.focusAr : source.focusEn;

  const categoryIcon =
    source.category === 'digital' ? (
      <FlaskConical className="w-4 h-4 text-indigo-500" />
    ) : source.category === 'english' ? (
      <Globe className="w-4 h-4 text-indigo-500" />
    ) : (
      <BookOpen className="w-4 h-4 text-teal-600" />
    );

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm hover:border-teal-200 hover:shadow-md transition-all">
      <div className={clsx('flex items-start gap-3', isRtl && 'flex-row-reverse')}>

        {/* Icon */}
        <div className="p-2 bg-gray-50 rounded-lg border border-gray-100 shrink-0">
          {categoryIcon}
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">

          {/* Title row */}
          <div className={clsx('flex items-start justify-between gap-2 mb-1', isRtl && 'flex-row-reverse')}>
            <h3 className={clsx(
              'font-bold text-gray-900 text-base leading-tight',
              source.category === 'arabic' || isRtl ? 'font-arabic' : ''
            )} dir={source.category === 'arabic' ? 'rtl' : undefined}>
              {title}
            </h3>
            <span className={clsx(
              'shrink-0 inline-flex items-center gap-1 text-xs font-medium',
              'bg-teal-50 text-teal-700 border border-teal-200 rounded-full px-2.5 py-0.5',
              isRtl && 'font-arabic'
            )}>
              <Clock className="w-3 h-3" />
              {t('vocab_source_status_planned', language)}
            </span>
          </div>

          {/* Author */}
          <p className={clsx(
            'text-sm text-gray-500 mb-2',
            source.category === 'arabic' || isRtl ? 'font-arabic text-right' : ''
          )} dir={source.category === 'arabic' ? 'rtl' : undefined}>
            {author}
          </p>

          {/* Era + volumes badges */}
          <div className={clsx('flex flex-wrap gap-2 mb-2.5', isRtl && 'flex-row-reverse')}>
            <span className={clsx(
              'inline-flex items-center gap-1 text-xs text-gray-600 bg-gray-100 border border-gray-200 rounded-md px-2 py-0.5',
              isRtl && 'font-arabic'
            )}>
              <span className="text-gray-400">{t('vocab_source_era_label', language)}</span>
              <span dir={source.category === 'arabic' ? 'rtl' : undefined}>{era}</span>
            </span>
            {source.volumes && (
              <span className={clsx(
                'inline-flex items-center gap-1 text-xs text-indigo-600 bg-indigo-50 border border-indigo-100 rounded-md px-2 py-0.5',
                isRtl && 'font-arabic'
              )}>
                <span className="text-indigo-400">{t('vocab_source_volumes_label', language)}</span>
                <strong>{source.volumes}</strong>
              </span>
            )}
          </div>

          {/* Focus description */}
          <p className={clsx(
            'text-sm text-gray-600 leading-relaxed',
            isRtl || source.category === 'arabic' ? 'font-arabic text-right' : ''
          )} dir={isRtl || source.category === 'arabic' ? 'rtl' : 'ltr'}>
            <span className={clsx('text-gray-400 text-xs me-1', isRtl && 'font-arabic')}>
              {t('vocab_source_focus_label', language)}
            </span>
            {focus}
          </p>
        </div>
      </div>
    </div>
  );
}
