/**
 * Phase F — Quranic Vocabulary / Gharib Al-Quran
 *
 * Safe placeholder page. Displays a search UI and returns the safe-refusal
 * message until a verified classical lexicon is integrated.
 *
 * Per policy: word meanings must NEVER be generated by AI alone.
 */
import { useState } from 'react';
import { Search, BookOpen, AlertCircle, Clock, ChevronRight } from 'lucide-react';
import { useLanguageStore } from '../../stores/languageStore';
import { t } from '../../i18n/translations';
import { vocabularyApi, VocabularyResponse } from '../../lib/api';
import clsx from 'clsx';

const PLANNED_SOURCE_NAMES: Record<string, { ar: string; en: string }> = {
  lisan_al_arab: { ar: 'لسان العرب (ابن منظور)', en: "Lisan Al-Arab (Ibn Manzur)" },
  mufradat_al_raghib: { ar: 'مفردات الراغب الأصفهاني', en: "Mufradat Al-Raghib Al-Isfahani" },
  qamus_al_muhit: { ar: 'القاموس المحيط (الفيروزآبادي)', en: "Al-Qamus Al-Muhit (Al-Fayruzabadi)" },
  lanes_lexicon: { ar: 'معجم لين العربي', en: "Lane's Arabic-English Lexicon" },
};

export function VocabularyPage() {
  const { language } = useLanguageStore();
  const isRtl = language === 'ar';

  const [query, setQuery] = useState('');
  const [result, setResult] = useState<VocabularyResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSearch(e: React.FormEvent) {
    e.preventDefault();
    const word = query.trim();
    if (!word) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await vocabularyApi.lookup(word);
      setResult(res.data);
    } catch {
      setError(language === 'ar' ? 'حدث خطأ. حاول مجدداً.' : 'An error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8" dir={isRtl ? 'rtl' : 'ltr'}>
      {/* Header */}
      <div className="mb-8 text-center">
        <div className="flex items-center justify-center gap-3 mb-3">
          <div className="p-3 bg-teal-50 rounded-xl">
            <BookOpen className="w-8 h-8 text-teal-600" />
          </div>
        </div>
        <h1 className={clsx('text-3xl font-bold text-gray-900 mb-2', isRtl && 'font-arabic')}>
          {t('vocab_page_title', language)}
        </h1>
        <p className={clsx('text-gray-600 max-w-xl mx-auto', isRtl && 'font-arabic')}>
          {t('vocab_page_subtitle', language)}
        </p>
      </div>

      {/* Search form */}
      <form onSubmit={handleSearch} className="mb-8">
        <div className="flex gap-3">
          <div className="relative flex-1">
            <Search className={clsx(
              'absolute top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400',
              isRtl ? 'right-3' : 'left-3'
            )} />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={t('vocab_search_placeholder', language)}
              className={clsx(
                'w-full border border-gray-300 rounded-lg py-3 text-base',
                'focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-teal-500',
                isRtl ? 'pr-10 pl-4 text-right font-arabic' : 'pl-10 pr-4'
              )}
              dir={isRtl ? 'rtl' : 'ltr'}
            />
          </div>
          <button
            type="submit"
            disabled={loading || !query.trim()}
            className={clsx(
              'px-6 py-3 bg-teal-600 text-white rounded-lg font-medium',
              'hover:bg-teal-700 transition-colors',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              isRtl && 'font-arabic'
            )}
          >
            {loading ? '...' : t('vocab_search_button', language)}
          </button>
        </div>
      </form>

      {/* Error */}
      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 p-4 mb-6">
          <p className={clsx('text-red-700 text-sm', isRtl && 'text-right font-arabic')}>{error}</p>
        </div>
      )}

      {/* Result: safe-refusal state */}
      {result && result.status === 'no_verified_source' && (
        <SafeRefusalCard result={result} language={language} isRtl={isRtl} />
      )}

      {/* Default state — no search yet */}
      {!result && !error && !loading && (
        <PlannedFeatureCard language={language} isRtl={isRtl} />
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Safe refusal card — shown when search returns no_verified_source
// ---------------------------------------------------------------------------

interface CardProps {
  language: 'ar' | 'en';
  isRtl: boolean;
}

interface SafeRefusalCardProps extends CardProps {
  result: VocabularyResponse;
}

function SafeRefusalCard({ result, language, isRtl }: SafeRefusalCardProps) {
  const message = language === 'ar' ? result.message_ar : result.message_en;

  return (
    <div className="rounded-xl border border-amber-200 bg-amber-50 p-6">
      <div className={clsx('flex items-start gap-3', isRtl && 'flex-row-reverse')}>
        <AlertCircle className="w-6 h-6 text-amber-600 mt-0.5 shrink-0" />
        <div className="flex-1">
          <h2 className={clsx('font-semibold text-amber-900 mb-2', isRtl && 'text-right font-arabic')}>
            <span dir={isRtl ? 'rtl' : 'ltr'}>{t('vocab_no_source_title', language)}</span>
            {' '}—{' '}
            <span dir="rtl" className="font-arabic">{result.word}</span>
          </h2>
          <p className={clsx('text-amber-800 text-sm leading-relaxed', isRtl && 'text-right font-arabic')}
             dir={isRtl ? 'rtl' : 'ltr'}>
            {message}
          </p>
          <span className={clsx(
            'mt-3 inline-flex items-center gap-1 text-xs font-medium text-amber-700',
            'bg-amber-100 border border-amber-300 rounded-full px-3 py-1',
            isRtl && 'font-arabic'
          )}>
            <Clock className="w-3.5 h-3.5" />
            {t('vocab_planned_label', language)}
          </span>
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Planned feature card — shown on initial load
// ---------------------------------------------------------------------------

function PlannedFeatureCard({ language, isRtl }: CardProps) {
  const plannedSourceKeys = ['lisan_al_arab', 'mufradat_al_raghib', 'qamus_al_muhit', 'lanes_lexicon'];

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
      <div className={clsx('flex items-center gap-2 mb-4', isRtl && 'flex-row-reverse')}>
        <Clock className="w-5 h-5 text-teal-600" />
        <span className={clsx('font-semibold text-gray-800', isRtl && 'font-arabic')}>
          {t('vocab_planned_label', language)}
        </span>
      </div>
      <p className={clsx('text-sm text-gray-600 mb-5', isRtl && 'text-right font-arabic')}
         dir={isRtl ? 'rtl' : 'ltr'}>
        {language === 'ar'
          ? 'هذه الميزة قيد التطوير. ستتيح البحث في معاني الكلمات القرآنية من معاجم عربية كلاسيكية موثوقة — دون توليد المعنى بالذكاء الاصطناعي وحده.'
          : 'This feature is under development. It will allow looking up Quranic word meanings from verified classical Arabic lexicons — never generating meanings from AI alone.'}
      </p>
      <p className={clsx('text-xs font-medium text-gray-500 mb-3', isRtl && 'text-right font-arabic')}>
        {t('vocab_planned_sources_label', language)}
      </p>
      <ul className="space-y-2">
        {plannedSourceKeys.map((key) => {
          const names = PLANNED_SOURCE_NAMES[key];
          return (
            <li key={key} className={clsx('flex items-center gap-2 text-sm text-gray-700', isRtl && 'flex-row-reverse')}>
              <ChevronRight className={clsx('w-4 h-4 text-teal-500 shrink-0', isRtl && 'rotate-180')} />
              <span dir={isRtl ? 'rtl' : 'ltr'} className={isRtl ? 'font-arabic' : ''}>
                {isRtl ? names.ar : names.en}
              </span>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
