/**
 * Canonical Quran people index.
 *
 * Provides a stable personId for every Quranic figure surfaced by the
 * story registry. Prophets are not duplicated here — their canonical IDs
 * live in `frontend/src/data/generated/quranProphetsAtlas.json` and are
 * imported by the build script. This file covers everyone else
 * (antagonists, righteous figures, monarchs, companions, family members,
 * angels, unseen beings, and collective groups).
 *
 * Used by:
 *   - scripts/build-quran-story-registry.ts (to populate RegistryStoryEntry.peopleIds)
 *   - scripts/validate-quran-story-registry.ts (to validate the IDs)
 *
 * Editing rules:
 *   - personId must be lowercase snake_case prefixed with `person_`.
 *   - aliases is the *raw* set of strings that may appear in
 *     data/manifests/stories.json #main_figures for this person.
 *     Variants like "Fir'awn" / "Firawn" / "Pharaoh" / "فرعون" all map
 *     to person_firawn. Comparison is case-insensitive and apostrophe-
 *     insensitive at build time, so aliases here can stay readable.
 *   - role is the primary bucket — pick the most defining one when a
 *     figure could fit two (e.g. Iblis is an antagonist *and* an unseen
 *     being; we list him as antagonist because that's the lens his
 *     stories use).
 *   - Add new people by appending to the appropriate role block.
 */

import type { PersonIndexEntry } from '../frontend/src/types/quranStoryRegistry';

export const QURAN_PEOPLE_INDEX: PersonIndexEntry[] = [
  // -------------------------------------------------------------------
  // Antagonists / opposing figures
  // -------------------------------------------------------------------
  {
    personId: 'person_firawn',
    nameArabic: 'فرعون',
    nameEnglish: "Fir'awn (Pharaoh)",
    role: 'antagonist',
    noteEnglish: 'The Egyptian tyrant who opposed Musa.',
    noteArabic: 'طاغية مصر الذي عارض موسى عليه السلام.',
  },
  {
    personId: 'person_haman',
    nameArabic: 'هامان',
    nameEnglish: 'Haman',
    role: 'antagonist',
    noteEnglish: "Fir'awn's chief minister.",
    noteArabic: 'وزير فرعون وقائد بنائه.',
  },
  {
    personId: 'person_qarun',
    nameArabic: 'قارون',
    nameEnglish: 'Qarun (Korah)',
    role: 'antagonist',
    noteEnglish: 'A wealthy man from the people of Musa, swallowed by the earth.',
    noteArabic: 'رجل غني من قوم موسى، خسف الله به الأرض.',
  },
  {
    personId: 'person_nimrod',
    nameArabic: 'نمرود',
    nameEnglish: 'Nimrod',
    role: 'antagonist',
    noteEnglish: "The king who disputed with Ibrahim and ordered the fire.",
    noteArabic: 'الملك الذي حاجّ إبراهيم وأمر بالنار.',
  },
  {
    personId: 'person_abu_lahab',
    nameArabic: 'أبو لهب',
    nameEnglish: 'Abu Lahab',
    role: 'antagonist',
    noteEnglish: 'An uncle of the Prophet ﷺ named in Surah Al-Masad.',
    noteArabic: 'عم النبي ﷺ المذكور في سورة المسد.',
  },
  {
    personId: 'person_samiri',
    nameArabic: 'السامري',
    nameEnglish: 'As-Samiri',
    role: 'antagonist',
    noteEnglish: 'The man who fashioned the golden calf for Bani Israel.',
    noteArabic: 'الذي صنع العجل لبني إسرائيل.',
  },
  {
    personId: 'person_iblis',
    nameArabic: 'إبليس',
    nameEnglish: 'Iblis',
    role: 'antagonist',
    noteEnglish: 'Refused to prostrate to Adam; sworn enemy of humankind.',
    noteArabic: 'رفض السجود لآدم، عدو الإنسان.',
  },
  {
    personId: 'person_balam',
    nameArabic: "بلعام بن باعوراء",
    nameEnglish: "Bal'am ibn Ba'ura",
    role: 'antagonist',
    noteEnglish: 'The scholar whose example is referenced in Surah Al-Aʿraf.',
    noteArabic: 'العالم الذي ضرب الله مثله في سورة الأعراف.',
  },
  {
    personId: 'person_jalut',
    nameArabic: 'جالوت',
    nameEnglish: 'Jalut (Goliath)',
    role: 'antagonist',
    noteEnglish: 'Defeated by Dawud in the army of Talut.',
    noteArabic: 'قتله داوود في جيش طالوت.',
  },

  // -------------------------------------------------------------------
  // Righteous figures (non-prophet)
  // -------------------------------------------------------------------
  {
    personId: 'person_maryam',
    nameArabic: 'مريم بنت عمران',
    nameEnglish: 'Maryam (Mary)',
    role: 'righteous_figure',
    noteEnglish: 'Mother of Isa; the only woman named explicitly in the Quran.',
    noteArabic: 'أم عيسى عليه السلام، المرأة الوحيدة المسماة في القرآن.',
  },
  {
    personId: 'person_asiya',
    nameArabic: 'آسية بنت مزاحم',
    nameEnglish: 'Asiya (wife of Pharaoh)',
    role: 'righteous_figure',
    noteEnglish: "Believing wife of Fir'awn, praised in Surah At-Tahrim.",
    noteArabic: 'زوجة فرعون المؤمنة، ضرب الله بها مثلاً.',
  },
  {
    personId: 'person_luqman',
    nameArabic: 'لقمان الحكيم',
    nameEnglish: 'Luqman the Wise',
    role: 'righteous_figure',
    noteEnglish: 'Sage whose counsel to his son is recorded in his surah.',
    noteArabic: 'الحكيم الذي ذُكرت وصيته لابنه في سورته.',
  },
  {
    personId: 'person_khidr',
    nameArabic: 'الخضر',
    nameEnglish: 'Al-Khidr',
    role: 'righteous_figure',
    noteEnglish: "Servant of Allah who taught Musa hidden knowledge.",
    noteArabic: 'العبد الصالح الذي علم موسى علماً.',
  },
  {
    personId: 'person_mother_musa',
    nameArabic: 'أم موسى',
    nameEnglish: 'Mother of Musa',
    role: 'righteous_figure',
    noteEnglish: 'Inspired to place infant Musa in the river.',
    noteArabic: 'أُوحي إليها أن تلقي موسى في اليم.',
  },
  {
    personId: 'person_believer_firaun',
    nameArabic: 'مؤمن آل فرعون',
    nameEnglish: "Believer from Pharaoh's family",
    role: 'righteous_figure',
    noteEnglish: 'Concealed his faith; spoke in defence of Musa.',
    noteArabic: 'كتم إيمانه ودافع عن موسى.',
  },
  {
    personId: 'person_imran_wife',
    nameArabic: 'امرأة عمران',
    nameEnglish: "Wife of Imran (mother of Maryam)",
    role: 'righteous_figure',
    noteEnglish: 'Dedicated Maryam to the service of the Sacred House.',
    noteArabic: 'نذرت ابنتها مريم لخدمة بيت المقدس.',
  },
  {
    personId: 'person_uzair',
    nameArabic: 'عزير',
    nameEnglish: "Uzair (Ezra)",
    role: 'righteous_figure',
    noteEnglish: 'The man whom Allah caused to die for a hundred years.',
    noteArabic: 'الذي أماته الله مئة عام ثم بعثه.',
  },
  {
    personId: 'person_zulaykha',
    nameArabic: 'امرأة العزيز (زليخا)',
    nameEnglish: 'Wife of Al-Aziz (tradition: Zulaykha)',
    role: 'righteous_figure',
    noteEnglish: 'Featured in the story of Yusuf in Egypt.',
    noteArabic: 'وردت قصتها مع يوسف في مصر.',
  },

  // -------------------------------------------------------------------
  // Monarchs (kings & queens, including pre-Islamic rulers)
  // -------------------------------------------------------------------
  {
    personId: 'person_bilqis',
    nameArabic: 'بلقيس ملكة سبأ',
    nameEnglish: 'Bilqis (Queen of Sheba)',
    role: 'monarch',
    noteEnglish: 'The queen who accepted Islam at the time of Sulayman.',
    noteArabic: 'الملكة التي أسلمت في عهد سليمان.',
  },
  {
    personId: 'person_talut',
    nameArabic: 'طالوت',
    nameEnglish: 'Talut (Saul)',
    role: 'monarch',
    noteEnglish: 'King appointed for Bani Israel before the battle with Jalut.',
    noteArabic: 'الملك الذي بعثه الله لبني إسرائيل قبل قتال جالوت.',
  },
  {
    personId: 'person_dhulqarnayn',
    nameArabic: 'ذو القرنين',
    nameEnglish: 'Dhul-Qarnayn',
    role: 'monarch',
    noteEnglish: 'The traveller-king who built the barrier against Yaʾjuj wa Maʾjuj.',
    noteArabic: 'الملك الرحالة الذي بنى السد دون يأجوج ومأجوج.',
  },
  {
    personId: 'person_aziz_egypt',
    nameArabic: 'عزيز مصر',
    nameEnglish: 'Al-Aziz of Egypt',
    role: 'monarch',
    noteEnglish: 'The minister of Egypt who bought Yusuf.',
    noteArabic: 'الذي اشترى يوسف وكان من علية مصر.',
  },
  {
    personId: 'person_abraha',
    nameArabic: 'أبرهة الأشرم',
    nameEnglish: 'Abraha',
    role: 'monarch',
    noteEnglish: 'Led the army of the elephant against the Kaʿba.',
    noteArabic: 'قائد جيش الفيل الذي قصد الكعبة.',
  },

  // -------------------------------------------------------------------
  // Companions of the Prophet ﷺ
  // -------------------------------------------------------------------
  {
    personId: 'person_aisha',
    nameArabic: 'عائشة بنت أبي بكر',
    nameEnglish: "ʿAisha bint Abi Bakr",
    role: 'companion',
    noteEnglish: 'Subject of the Ifk revelation in Surah An-Nur.',
    noteArabic: 'نزلت آيات الإفك في تبرئتها.',
  },
  {
    personId: 'person_abu_bakr',
    nameArabic: 'أبو بكر الصديق',
    nameEnglish: 'Abu Bakr As-Siddiq',
    role: 'companion',
    noteEnglish: 'Companion of the Prophet ﷺ in the cave during the Hijrah.',
    noteArabic: 'صاحب النبي ﷺ في الغار في الهجرة.',
  },
  {
    personId: 'person_ibn_umm_maktum',
    nameArabic: 'ابن أم مكتوم',
    nameEnglish: 'Ibn Umm Maktum',
    role: 'companion',
    noteEnglish: 'The blind companion referenced in Surah ʿAbasa.',
    noteArabic: 'الصحابي الأعمى الذي نزلت فيه آيات سورة عبس.',
  },

  // -------------------------------------------------------------------
  // Family members (named in stories without standing alone)
  // -------------------------------------------------------------------
  {
    personId: 'person_hawwa',
    nameArabic: 'حواء',
    nameEnglish: 'Hawwa (Eve)',
    role: 'family_member',
    noteEnglish: "Adam's wife in Paradise and on Earth.",
    noteArabic: 'زوج آدم عليه السلام.',
  },
  {
    personId: 'person_sarah',
    nameArabic: 'سارة',
    nameEnglish: 'Sarah',
    role: 'family_member',
    noteEnglish: 'Wife of Ibrahim, mother of Ishaq.',
    noteArabic: 'زوجة إبراهيم وأم إسحاق.',
  },
  {
    personId: 'person_hajar',
    nameArabic: 'هاجر',
    nameEnglish: 'Hajar',
    role: 'family_member',
    noteEnglish: 'Mother of Ismail in Makkah.',
    noteArabic: 'أم إسماعيل في مكة.',
  },
  {
    personId: 'person_wife_nuh',
    nameArabic: 'امرأة نوح',
    nameEnglish: 'Wife of Nuh',
    role: 'family_member',
    noteEnglish: 'Example of disbelief among prophets’ wives.',
    noteArabic: 'ضرب الله بها مثلاً للذين كفروا.',
  },
  {
    personId: 'person_wife_lut',
    nameArabic: 'امرأة لوط',
    nameEnglish: 'Wife of Lut',
    role: 'family_member',
    noteEnglish: 'Example of disbelief among prophets’ wives.',
    noteArabic: 'مثل آخر في سورة التحريم.',
  },
  {
    personId: 'person_son_nuh',
    nameArabic: 'ابن نوح',
    nameEnglish: 'Son of Nuh',
    role: 'family_member',
    noteEnglish: 'Drowned in the Flood despite his father’s call.',
    noteArabic: 'غرق في الطوفان رغم نداء أبيه.',
  },
  {
    personId: 'person_brothers_yusuf',
    nameArabic: 'إخوة يوسف',
    nameEnglish: 'Brothers of Yusuf',
    role: 'family_member',
    noteEnglish: 'Cast Yusuf into the well; later repented in Egypt.',
    noteArabic: 'ألقوا يوسف في الجب ثم تابوا في مصر.',
  },
  {
    personId: 'person_father_ibrahim',
    nameArabic: 'آزر (والد إبراهيم)',
    nameEnglish: 'Azar (father of Ibrahim)',
    role: 'family_member',
    noteEnglish: 'Father of Ibrahim, an idol-carver in his community.',
    noteArabic: 'والد إبراهيم، كان يصنع الأصنام.',
  },
  // -------------------------------------------------------------------
  // Angels
  // -------------------------------------------------------------------
  {
    personId: 'person_jibril',
    nameArabic: 'جبريل',
    nameEnglish: 'Jibril (Gabriel)',
    role: 'angel',
    noteEnglish: 'The angel of revelation; carried the Quran to the Prophet ﷺ.',
    noteArabic: 'الملك الموكل بالوحي.',
  },
  {
    personId: 'person_israfil',
    nameArabic: 'إسرافيل',
    nameEnglish: 'Israfil',
    role: 'angel',
    noteEnglish: 'The angel who will blow the trumpet of resurrection.',
    noteArabic: 'الملك الموكل بالنفخ في الصور.',
  },
  {
    personId: 'person_mikail',
    nameArabic: 'ميكائيل',
    nameEnglish: 'Mikail (Michael)',
    role: 'angel',
  },
  {
    personId: 'person_harut',
    nameArabic: 'هاروت',
    nameEnglish: 'Harut',
    role: 'angel',
    noteEnglish: 'Mentioned with Marut in Surah Al-Baqarah.',
    noteArabic: 'مذكور مع ماروت في سورة البقرة.',
  },
  {
    personId: 'person_marut',
    nameArabic: 'ماروت',
    nameEnglish: 'Marut',
    role: 'angel',
    noteEnglish: 'Mentioned with Harut in Surah Al-Baqarah.',
    noteArabic: 'مذكور مع هاروت في سورة البقرة.',
  },
  {
    personId: 'person_angels_generic',
    nameArabic: 'الملائكة',
    nameEnglish: 'Angels (generic)',
    role: 'angel',
    noteEnglish: 'Unnamed angels who prostrated to Adam and serve at the Throne.',
    noteArabic: 'الملائكة الذين سجدوا لآدم وحملة العرش.',
  },

  // -------------------------------------------------------------------
  // Unseen beings
  // -------------------------------------------------------------------
  {
    personId: 'person_jinn_generic',
    nameArabic: 'الجن',
    nameEnglish: 'Jinn',
    role: 'unseen_being',
    noteEnglish: 'A separate creation; some Jinn listened to the Quran from the Prophet ﷺ.',
    noteArabic: 'خلق مستقل، استمع بعضهم للقرآن من النبي ﷺ.',
  },
  {
    personId: 'person_yajuj',
    nameArabic: 'يأجوج',
    nameEnglish: 'Yaʾjuj (Gog)',
    role: 'unseen_being',
  },
  {
    personId: 'person_majuj',
    nameArabic: 'مأجوج',
    nameEnglish: 'Maʾjuj (Magog)',
    role: 'unseen_being',
  },

  // -------------------------------------------------------------------
  // Collective groups (multiple unnamed individuals treated as one entity)
  // -------------------------------------------------------------------
  {
    personId: 'person_youth_cave',
    nameArabic: 'فتية الكهف',
    nameEnglish: 'Youth of the Cave',
    role: 'collective',
    noteEnglish: 'The believers who took refuge in the cave with their dog.',
    noteArabic: 'الفتية الذين آووا إلى الكهف.',
  },
  {
    personId: 'person_magicians_firaun',
    nameArabic: 'سحرة فرعون',
    nameEnglish: "Magicians of Pharaoh",
    role: 'collective',
    noteEnglish: 'Believed in the Lord of Musa after the contest.',
    noteArabic: 'آمنوا بربّ موسى بعد المواجهة.',
  },
  {
    personId: 'person_disciples_isa',
    nameArabic: 'الحواريون',
    nameEnglish: 'Disciples of Isa',
    role: 'collective',
    noteEnglish: "Helpers of Isa who asked for the heavenly table-spread.",
    noteArabic: 'أنصار عيسى الذين سألوا المائدة.',
  },
  {
    personId: 'person_bani_israel',
    nameArabic: 'بنو إسرائيل',
    nameEnglish: 'Bani Israel (Children of Israel)',
    role: 'collective',
  },
  {
    personId: 'person_people_nuh',
    nameArabic: 'قوم نوح',
    nameEnglish: 'People of Nuh',
    role: 'collective',
  },
  {
    personId: 'person_people_ad',
    nameArabic: 'عاد',
    nameEnglish: "People of 'Ad",
    role: 'collective',
  },
  {
    personId: 'person_people_thamud',
    nameArabic: 'ثمود',
    nameEnglish: 'Thamud',
    role: 'collective',
  },
  {
    personId: 'person_people_lut',
    nameArabic: 'قوم لوط',
    nameEnglish: 'People of Lut',
    role: 'collective',
  },
  {
    personId: 'person_people_madyan',
    nameArabic: 'أهل مدين',
    nameEnglish: 'People of Madyan',
    role: 'collective',
  },
  {
    personId: 'person_people_saba',
    nameArabic: 'أهل سبأ',
    nameEnglish: 'People of Sheba',
    role: 'collective',
  },
  {
    personId: 'person_people_tubba',
    nameArabic: 'قوم تُبَّع',
    nameEnglish: 'People of Tubbaʿ',
    role: 'collective',
  },
  {
    personId: 'person_people_rass',
    nameArabic: 'أصحاب الرس',
    nameEnglish: 'People of Ar-Rass',
    role: 'collective',
  },
  {
    personId: 'person_people_ayka',
    nameArabic: 'أصحاب الأيكة',
    nameEnglish: 'People of the Thicket',
    role: 'collective',
  },
  {
    personId: 'person_people_ditch',
    nameArabic: 'أصحاب الأخدود',
    nameEnglish: 'People of the Ditch',
    role: 'collective',
  },
  {
    personId: 'person_people_elephant',
    nameArabic: 'أصحاب الفيل',
    nameEnglish: 'Army of the Elephant',
    role: 'collective',
  },
  {
    personId: 'person_three_messengers',
    nameArabic: 'المرسلون الثلاثة',
    nameEnglish: 'Three Messengers (Ya-Sin)',
    role: 'collective',
  },
  {
    personId: 'person_garden_owners',
    nameArabic: 'أصحاب الجنة',
    nameEnglish: 'Owners of the Garden',
    role: 'collective',
  },
  {
    personId: 'person_hypocrites_madinah',
    nameArabic: 'المنافقون',
    nameEnglish: 'The Hypocrites (in Madinah)',
    role: 'collective',
  },
  {
    personId: 'person_romans',
    nameArabic: 'الروم',
    nameEnglish: 'The Romans (Byzantines)',
    role: 'collective',
    noteEnglish: 'Subject of the opening prediction in Surah Ar-Rum (30:1-5).',
    noteArabic: 'موضوع نبوءة افتتاح سورة الروم (٣٠: ١-٥).',
  },
  {
    personId: 'person_persians',
    nameArabic: 'الفرس',
    nameEnglish: 'The Persians (Sassanians)',
    role: 'collective',
    noteEnglish: 'Defeated the Romans before the Romans’ predicted victory in Surah Ar-Rum.',
    noteArabic: 'هزموا الروم ثم انتصر الروم كما نزلت السورة.',
  },
  {
    personId: 'person_confederates',
    nameArabic: 'الأحزاب',
    nameEnglish: 'The Confederates (Ahzab)',
    role: 'collective',
    noteEnglish: 'Tribal coalition that besieged Madinah in the Battle of the Trench.',
    noteArabic: 'تحالف القبائل في غزوة الخندق.',
  },
  {
    personId: 'person_sabbath_breakers',
    nameArabic: 'أصحاب السبت',
    nameEnglish: 'People of the Sabbath',
    role: 'collective',
    noteEnglish: 'The villagers transformed for breaking the Sabbath.',
    noteArabic: 'القرية التي مُسخ أهلها لاعتدائهم في السبت.',
  },
  // -------------------------------------------------------------------
  // Other named individuals (kept under family for navigation; not strictly
  // family members — these are biblical figures with one-shot appearances)
  // -------------------------------------------------------------------
  {
    personId: 'person_habil',
    nameArabic: 'هابيل',
    nameEnglish: 'Habil (Abel)',
    role: 'family_member',
    noteEnglish: 'One of the two sons of Adam in Surah Al-Maʾida.',
    noteArabic: 'أحد ابني آدم في سورة المائدة.',
  },
  {
    personId: 'person_qabil',
    nameArabic: 'قابيل',
    nameEnglish: 'Qabil (Cain)',
    role: 'family_member',
    noteEnglish: 'The brother who committed the first murder.',
    noteArabic: 'الأخ الذي ارتكب أول جريمة قتل.',
  },
];

/**
 * Manually-curated alias → personId map. Any string appearing in
 * stories.json#main_figures (case-insensitive, apostrophes ignored) that
 * matches one of these keys resolves to the canonical personId.
 *
 * Aliases also include common spelling variants (Fir'awn, Firawn, Pharaoh)
 * and the Arabic name so the build can pick up both languages.
 */
export const PERSON_ALIASES: Record<string, string> = {
  // antagonists
  "firawn": 'person_firawn',
  "fir'awn": 'person_firawn',
  'pharaoh': 'person_firawn',
  'فرعون': 'person_firawn',
  'figure_firawn': 'person_firawn',
  'haman': 'person_haman',
  'هامان': 'person_haman',
  'qarun': 'person_qarun',
  'korah': 'person_qarun',
  'قارون': 'person_qarun',
  'nimrod': 'person_nimrod',
  'namrud': 'person_nimrod',
  'نمرود': 'person_nimrod',
  'abu lahab': 'person_abu_lahab',
  'أبو لهب': 'person_abu_lahab',
  'samiri': 'person_samiri',
  'as-samiri': 'person_samiri',
  'السامري': 'person_samiri',
  'iblis': 'person_iblis',
  'إبليس': 'person_iblis',
  "bal'am ibn ba'ura": 'person_balam',
  "balam ibn baura": 'person_balam',
  'jalut': 'person_jalut',
  'jalut (goliath)': 'person_jalut',
  'goliath': 'person_jalut',
  'جالوت': 'person_jalut',

  // righteous
  'maryam': 'person_maryam',
  'mary': 'person_maryam',
  'مريم': 'person_maryam',
  'figure_maryam': 'person_maryam',
  'asiya': 'person_asiya',
  'luqman': 'person_luqman',
  'khidr': 'person_khidr',
  'al-khidr': 'person_khidr',
  "mother of musa": 'person_mother_musa',
  "believer of fir'awn": 'person_believer_firaun',
  'believer of firawn': 'person_believer_firaun',
  "imran's wife": 'person_imran_wife',
  'wife of imran': 'person_imran_wife',
  'uzair': 'person_uzair',
  'ezra': 'person_uzair',
  'zulaykha': 'person_zulaykha',

  // monarchs
  'bilqis': 'person_bilqis',
  'queen of sheba': 'person_bilqis',
  'figure_bilqis': 'person_bilqis',
  'talut': 'person_talut',
  'talut (saul)': 'person_talut',
  'saul': 'person_talut',
  'طالوت': 'person_talut',
  'dhul-qarnayn': 'person_dhulqarnayn',
  'dhulqarnayn': 'person_dhulqarnayn',
  'ذو القرنين': 'person_dhulqarnayn',
  'aziz': 'person_aziz_egypt',
  'al-aziz': 'person_aziz_egypt',
  'abraha': 'person_abraha',

  // companions
  'aisha': 'person_aisha',
  "'aisha": 'person_aisha',
  'عائشة': 'person_aisha',
  'abu bakr': 'person_abu_bakr',
  'ibn umm maktum': 'person_ibn_umm_maktum',

  // family
  'hawwa': 'person_hawwa',
  'eve': 'person_hawwa',
  'حواء': 'person_hawwa',
  'sara': 'person_sarah',
  'sarah': 'person_sarah',
  'figure_sarah': 'person_sarah',
  'hajar': 'person_hajar',
  'wife of nuh': 'person_wife_nuh',
  'wife of lut': 'person_wife_lut',
  'son of nuh': 'person_son_nuh',
  "his son": 'person_son_nuh',
  'brothers': 'person_brothers_yusuf',
  'azar': 'person_father_ibrahim',
  'father of ibrahim': 'person_father_ibrahim',

  // angels
  'jibril': 'person_jibril',
  'gabriel': 'person_jibril',
  'israfil': 'person_israfil',
  'mikail': 'person_mikail',
  'michael': 'person_mikail',
  'harut': 'person_harut',
  'marut': 'person_marut',
  'angels': 'person_angels_generic',
  'الملائكة': 'person_angels_generic',

  // unseen beings
  'jinn': 'person_jinn_generic',
  'الجن': 'person_jinn_generic',
  'yajuj': 'person_yajuj',
  'يأجوج': 'person_yajuj',
  'majuj': 'person_majuj',
  'مأجوج': 'person_majuj',
  'yajuj and majuj': 'person_yajuj', // resolves to first; build emits both via storyId map below

  // prophets — common name variants used in stories.json#main_figures
  // mapped to the canonical prophet_X IDs from quranProphetsAtlas.json
  'adam': 'prophet_adam',
  'آدم': 'prophet_adam',
  'idris': 'prophet_idris',
  'nuh': 'prophet_nuh',
  'noah': 'prophet_nuh',
  'نوح': 'prophet_nuh',
  'hud': 'prophet_hud',
  'salih': 'prophet_salih',
  'ibrahim': 'prophet_ibrahim',
  'abraham': 'prophet_ibrahim',
  'إبراهيم': 'prophet_ibrahim',
  'lut': 'prophet_lut',
  'lot': 'prophet_lut',
  'ismail': 'prophet_ismail',
  'ishmael': 'prophet_ismail',
  'ishaq': 'prophet_ishaq',
  'isaac': 'prophet_ishaq',
  'yaqub': 'prophet_yaqub',
  "ya'qub": 'prophet_yaqub',
  'jacob': 'prophet_yaqub',
  'يعقوب': 'prophet_yaqub',
  'yusuf': 'prophet_yusuf',
  'joseph': 'prophet_yusuf',
  'يوسف': 'prophet_yusuf',
  'ayyub': 'prophet_ayyub',
  'job': 'prophet_ayyub',
  'shuayb': 'prophet_shuayb',
  "shu'ayb": 'prophet_shuayb',
  'شعيب': 'prophet_shuayb',
  'musa': 'prophet_musa',
  'moses': 'prophet_musa',
  'موسى': 'prophet_musa',
  'harun': 'prophet_harun',
  'aaron': 'prophet_harun',
  'dhul-kifl': 'prophet_dhulkifl',
  'dhulkifl': 'prophet_dhulkifl',
  'dawud': 'prophet_dawud',
  'daud': 'prophet_dawud',
  'david': 'prophet_dawud',
  'داوود': 'prophet_dawud',
  'sulayman': 'prophet_sulayman',
  'solomon': 'prophet_sulayman',
  'ilyas': 'prophet_ilyas',
  'elijah': 'prophet_ilyas',
  'al-yasa': 'prophet_alyasa',
  'alyasa': 'prophet_alyasa',
  'elisha': 'prophet_alyasa',
  'yunus': 'prophet_yunus',
  'jonah': 'prophet_yunus',
  'zakariyya': 'prophet_zakariyya',
  'zechariah': 'prophet_zakariyya',
  'yahya': 'prophet_yahya',
  'john': 'prophet_yahya',
  'isa': 'prophet_isa',
  'jesus': 'prophet_isa',
  'muhammad': 'prophet_muhammad',
  // Prophet IDs that may slip through as raw alias strings
  'prophet_ishaq': 'prophet_ishaq',
  'prophet_yaqub': 'prophet_yaqub',
  'prophet_harun': 'prophet_harun',
  'prophet_dhulkifl': 'prophet_dhulkifl',
  'prophet_ilyas': 'prophet_ilyas',
  'prophet_alyasa': 'prophet_alyasa',
  'prophet_sulayman': 'prophet_sulayman',
  'prophet_muhammad': 'prophet_muhammad',
  'prophet_ismail': 'prophet_ismail',
  // Tradition-name secondary figures
  'habil (abel)': 'person_habil',
  'habil': 'person_habil',
  'qabil (cain)': 'person_qabil',
  'qabil': 'person_qabil',
  'sons of adam': 'person_habil',
  'صاحب الجنتين': 'person_garden_owners',
  'صاحبه المؤمن': 'person_garden_owners',
  'villagers by the sea': 'person_sabbath_breakers',

  // collectives
  'youth of the cave': 'person_youth_cave',
  'magicians of pharaoh': 'person_magicians_firaun',
  'magicians': 'person_magicians_firaun',
  'disciples': 'person_disciples_isa',
  'bani israel': 'person_bani_israel',
  'bani israil': 'person_bani_israel',
  'children of israel': 'person_bani_israel',
  'his people': 'person_bani_israel', // weak default — overridden by storyId map where needed
  'people of madyan': 'person_people_madyan',
  'people of nuh': 'person_people_nuh',
  "people of 'ad": 'person_people_ad',
  'thamud': 'person_people_thamud',
  'people of saba': 'person_people_saba',
  'people of sheba': 'person_people_saba',
  'people of tubba': 'person_people_tubba',
  "تُبَّع": 'person_people_tubba',
  "أصحاب الرس": 'person_people_rass',
  "أصحاب الأيكة": 'person_people_ayka',
  "people of the elephant": 'person_people_elephant',
  'hypocrites': 'person_hypocrites_madinah',
  'منافقون': 'person_hypocrites_madinah',
  'المنافقون': 'person_hypocrites_madinah',
};

/**
 * Hand-authored extra peopleIds per story — for cases where mainFigures
 * is missing a relevant person, or where a vague placeholder like
 * "Brothers" needs a specific resolution. Build script unions these with
 * alias-resolved values.
 */
export const STORY_EXTRA_PEOPLE: Record<string, string[]> = {
  story_musa: ['person_firawn', 'person_haman', 'person_bani_israel'],
  story_musa_firaun_dialogue: ['person_firawn', 'person_haman'],
  story_magicians: ['person_firawn', 'person_magicians_firaun'],
  story_sea_crossing: ['person_firawn', 'person_bani_israel'],
  story_haman: ['person_haman', 'person_firawn'],
  story_qarun: ['person_qarun', 'person_bani_israel'],
  story_asiya: ['person_asiya', 'person_firawn'],
  story_mother_musa: ['person_mother_musa', 'person_firawn'],
  story_believer_firaun: ['person_believer_firaun', 'person_firawn'],
  story_samiri: ['person_samiri', 'person_bani_israel'],
  story_golden_calf: ['person_samiri', 'person_bani_israel'],
  story_abu_lahab: ['person_abu_lahab'],
  story_isa: ['person_maryam', 'person_disciples_isa'],
  story_maryam: ['person_maryam', 'person_imran_wife'],
  story_maryam_birth: ['person_maryam', 'person_imran_wife'],
  story_isa_miracles: ['person_disciples_isa', 'person_maryam'],
  story_yusuf: ['person_brothers_yusuf', 'person_aziz_egypt', 'person_zulaykha'],
  story_yusuf_brothers: ['person_brothers_yusuf'],
  story_yusuf_prison: ['person_aziz_egypt'],
  story_zulaykha: ['person_zulaykha', 'person_aziz_egypt'],
  story_kahf: ['person_youth_cave'],
  story_seven_sleepers_dog: ['person_youth_cave'],
  story_sleepers_numbers: ['person_youth_cave'],
  story_three_messengers: ['person_three_messengers'],
  story_garden_owners: ['person_garden_owners'],
  story_two_men: ['person_garden_owners'],
  story_bilqis: ['person_bilqis'],
  story_sulayman: ['person_bilqis'],
  story_talut_jalut: ['person_talut', 'person_jalut'],
  story_dhulqarnayn: ['person_dhulqarnayn', 'person_yajuj', 'person_majuj'],
  story_yajuj_majuj: ['person_yajuj', 'person_majuj'],
  story_uzair: ['person_uzair'],
  story_khidr: ['person_khidr'],
  story_ifk: ['person_aisha', 'person_hypocrites_madinah'],
  story_hijrah: ['person_abu_bakr'],
  story_abasa: ['person_ibn_umm_maktum'],
  story_elephant: ['person_abraha', 'person_people_elephant'],
  story_najran: ['person_disciples_isa'],
  story_ibrahim_nimrod: ['person_nimrod'],
  story_ibrahim_fire: ['person_nimrod'],
  story_adam: ['person_hawwa', 'person_iblis', 'person_angels_generic'],
  story_angels_prostration: ['person_angels_generic', 'person_iblis'],
  story_iblis_refusal: ['person_iblis'],
  story_jinn_quran: ['person_jinn_generic'],
  story_harut_marut: ['person_harut', 'person_marut'],
  story_bani_israel: ['person_bani_israel'],
  story_nuh_people: ['person_people_nuh'],
  story_ad: ['person_people_ad'],
  story_thamud: ['person_people_thamud'],
  story_madyan: ['person_people_madyan'],
  story_saba: ['person_people_saba'],
  story_tubba: ['person_people_tubba'],
  story_rass: ['person_people_rass'],
  story_ayka: ['person_people_ayka'],
  story_ditch: ['person_people_ditch'],
  story_lut: ['person_people_lut'],
  story_wife_nuh: ['person_wife_nuh'],
  story_wife_lut: ['person_wife_lut'],
  story_son_nuh: ['person_son_nuh'],
  story_dog_parable: ['person_balam'],
  story_ibrahim: ['person_father_ibrahim', 'person_sarah', 'person_hajar'],
  story_ibrahim_stars: ['person_father_ibrahim'],
  story_yaqub: ['person_brothers_yusuf'],
  story_habil_qabil: ['person_habil', 'person_qabil'],
  story_sabbath_breakers: ['person_sabbath_breakers', 'person_bani_israel'],
  story_village_fish: ['person_sabbath_breakers'],
  story_two_gardens: ['person_garden_owners'],
  story_ibrahim_birds: ['prophet_ibrahim'],
  story_ant_hoopoe: ['prophet_sulayman'],
  story_dawud_trial: ['prophet_dawud'],
  story_sulayman_jinn: ['prophet_sulayman', 'person_jinn_generic'],
  story_sulayman_horses: ['prophet_sulayman'],
  story_sulayman_trial: ['prophet_sulayman'],
  story_musa_mountain: ['prophet_musa'],
  story_musa_burning_bush: ['prophet_musa'],
  story_musa_midian: ['prophet_musa', 'prophet_shuayb'],
  story_isa_ascension: ['prophet_isa'],
  story_yusuf_dream: ['prophet_yusuf', 'prophet_yaqub'],
  story_yusuf_brothers: ['prophet_yusuf'],
  story_yusuf_prison: ['prophet_yusuf'],
  story_ismail: ['prophet_ismail', 'prophet_ibrahim', 'person_hajar'],
  story_dhulkifl: ['prophet_dhulkifl'],
  story_ilyas: ['prophet_ilyas'],
  story_alyasa: ['prophet_alyasa'],
  story_muhammad: ['prophet_muhammad'],
  story_badr: ['prophet_muhammad'],
  story_uhud: ['prophet_muhammad'],
  story_hudaybiyyah: ['prophet_muhammad'],
  story_conquest_makkah: ['prophet_muhammad'],
  story_qiblah_change: ['prophet_muhammad'],
  story_tabuk: ['prophet_muhammad'],
  story_intercession: ['prophet_muhammad'],
  story_covenant_souls: ['prophet_adam'],
  story_isra_miraj: ['prophet_muhammad', 'person_jibril'],
  story_khandaq: [
    'prophet_muhammad',
    'person_confederates',
    'person_hypocrites_madinah',
    'person_angels_generic',
  ],
  story_romans_persians: ['person_romans', 'person_persians'],
};
