/**
 * Hand-authored map of storyId → subcategory tags using the "group:tag"
 * convention defined in frontend/src/types/quranStoryRegistry.ts.
 *
 * Imported by scripts/build-quran-story-registry.ts which writes the
 * subcategories array into every RegistryStoryEntry.
 *
 * Editing rules:
 *   - Keep tags lowercase, snake_case.
 *   - Use only groups from SUBCATEGORY_GROUP_ORDER.
 *   - A story may carry multiple tags from the same group.
 *   - When a tag does not yet appear in SUBCATEGORY_TAG_LABELS, add it
 *     there too so the UI can render a bilingual label.
 *   - Subcategories are *not* a replacement for the top-level category;
 *     a story keeps its category (prophet / parable / nation / …) and
 *     gains a list of thematic subcategories on top.
 *
 * Coverage policy:
 *   - Every authored story (sourceType = "authored_story") should appear
 *     here at least once. Stories not listed simply get an empty
 *     subcategories array (no failure).
 */

export const STORY_SUBCATEGORY_MAP: Record<string, string[]> = {
  // --- Major prophets ---------------------------------------------------
  story_adam: [
    'event:creation',
    'event:fall_from_paradise',
    'family:husband_wife',
    'family:parent_child',
    'place:garden',
    'virtue:repentance',
    'vice:arrogance',
    'vice:disobedience',
  ],
  story_nuh: [
    'event:flood',
    'object:ship',
    'family:father',
    'family:son',
    'virtue:patience',
    'vice:disbelief',
    'nature:water',
    'place:mount_judi',
  ],
  story_ibrahim: [
    'miracle:fire_cool',
    'nature:fire',
    'nature:stars',
    'family:father',
    'family:son',
    'event:building_kaaba',
    'event:sacrifice',
    'place:makkah',
    'place:masjid_al_haram',
    'role:prophet',
    'virtue:trust_in_allah',
    'virtue:sincerity',
    'vice:idolatry',
  ],
  story_musa: [
    'miracle:sea_parting',
    'miracle:staff_to_serpent',
    'miracle:white_hand',
    'object:staff',
    'object:tablets',
    'object:manna_salwa',
    'place:egypt',
    'place:mount_sinai',
    'place:sea',
    'role:prophet',
    'event:exodus',
    'event:revelation',
    'virtue:patience',
    'vice:tyranny',
  ],
  story_yusuf: [
    'event:dream',
    'family:brothers',
    'family:father',
    'object:shirt_yusuf',
    'object:cup',
    'place:egypt',
    'place:well',
    'place:prison',
    'role:prophet',
    'role:slave',
    'virtue:patience',
    'virtue:chastity',
    'vice:jealousy',
    'vice:betrayal',
  ],
  story_isa: [
    'miracle:talking_baby',
    'miracle:bird_creation',
    'miracle:healing_blind',
    'miracle:healing_leper',
    'miracle:dead_revived',
    'object:table_spread',
    'family:mother',
    'role:prophet',
    'role:messenger',
    'virtue:mercy',
  ],
  story_maryam: [
    'miracle:talking_baby',
    'family:mother',
    'family:daughter',
    'virtue:chastity',
    'virtue:sincerity',
    'place:masjid_al_aqsa',
  ],
  story_zakariyya_yahya: [
    'family:father',
    'family:son',
    'role:prophet',
    'virtue:patience',
    'place:masjid_al_aqsa',
  ],
  story_sulayman: [
    'animal:hoopoe',
    'animal:ant',
    'animal:horse',
    'animal:birds',
    'object:throne',
    'object:ring',
    'role:king',
    'role:prophet',
    'miracle:throne_transport',
    'miracle:ant_speech',
    'miracle:hoopoe_speech',
    'nature:wind',
    'place:sheba',
  ],
  story_dawud: [
    'role:king',
    'role:prophet',
    'nature:mountain',
    'animal:birds',
    'event:battle',
    'event:judgment',
    'virtue:justice',
  ],
  story_ayyub: [
    'virtue:patience',
    'virtue:trust_in_allah',
    'event:trial',
    'family:husband_wife',
  ],
  story_yunus: [
    'animal:whale',
    'animal:fish',
    'miracle:fish_swallow',
    'place:sea',
    'virtue:repentance',
  ],
  story_lut: [
    'vice:disobedience',
    'vice:disbelief',
    'family:husband_wife',
    'event:flood',
    'role:prophet',
  ],
  story_shuayb: [
    'place:madyan',
    'place:thicket',
    'role:prophet',
    'virtue:justice',
    'vice:greed',
  ],
  story_salih: [
    'animal:camel',
    'miracle:she_camel',
    'place:hijr',
    'role:prophet',
    'vice:arrogance',
  ],
  story_hud: [
    'place:ad_lands',
    'role:prophet',
    'vice:arrogance',
    'nature:wind',
  ],
  // --- Cave & similar parables -----------------------------------------
  story_kahf: [
    'animal:dog',
    'place:cave',
    'miracle:cave_sleep',
    'virtue:patience',
    'virtue:trust_in_allah',
  ],
  story_dhulqarnayn: [
    'role:king',
    'object:mountain_lifted',
    'event:judgment',
    'virtue:justice',
  ],
  story_luqman: [
    'family:father',
    'family:son',
    'virtue:wisdom',
    'virtue:humility',
  ],
  story_qarun: [
    'place:egypt',
    'nature:earthquake',
    'vice:arrogance',
    'vice:greed',
  ],
  story_habil_qabil: [
    'animal:raven',
    'family:brothers',
    'event:first_murder',
    'event:sacrifice',
    'vice:jealousy',
  ],
  story_elephant: [
    'animal:elephant',
    'animal:birds',
    'miracle:elephant_birds',
    'place:makkah',
    'place:masjid_al_haram',
  ],
  story_baqarah_cow: [
    'animal:cow',
    'miracle:dead_revived',
    'event:judgment',
    'vice:disobedience',
  ],
  story_uzair: [
    'animal:donkey',
    'miracle:donkey_revived',
    'miracle:dead_revived',
  ],
  story_sabbath_breakers: [
    'animal:fish',
    'animal:monkey',
    'miracle:transformation_monkeys',
    'place:sea',
    'vice:disobedience',
  ],
  // --- Unseen / cosmic ---------------------------------------------------
  story_angels_prostration: ['event:creation', 'vice:arrogance'],
  story_jinn_quran: ['event:revelation'],
  story_yajuj_majuj: ['object:mountain_lifted', 'place:mount_judi'],
  story_two_gardens: [
    'place:two_gardens',
    'place:garden',
    'nature:plant',
    'vice:arrogance',
    'virtue:gratitude',
  ],
  story_good_word: ['nature:plant'],
  story_fly: ['animal:fly', 'vice:idolatry'],
  story_spider: ['animal:spider'],
  story_tubba: ['vice:disbelief'],
  story_rass: ['place:rass', 'vice:disbelief'],
  story_ayka: ['place:thicket', 'vice:disbelief'],
  story_talut_jalut: [
    'role:king',
    'object:ark_covenant',
    'event:battle',
    'virtue:courage',
  ],
  story_ifk: [
    'event:slander',
    'role:companion',
    'vice:slander',
  ],
  // --- More prophets -----------------------------------------------------
  story_idris: ['role:prophet'],
  story_ismail: [
    'event:sacrifice',
    'family:father',
    'family:son',
    'event:building_kaaba',
    'place:makkah',
    'place:masjid_al_haram',
    'role:prophet',
  ],
  story_dhulkifl: ['role:prophet', 'virtue:patience'],
  story_ilyas: ['role:prophet', 'vice:idolatry'],
  story_alyasa: ['role:prophet'],
  story_muhammad: [
    'role:prophet',
    'role:messenger',
    'event:revelation',
    'event:hijrah',
    'place:makkah',
    'place:madinah',
  ],
  // --- Parables / dialogue ----------------------------------------------
  story_garden_owners: ['place:garden', 'nature:plant', 'vice:arrogance'],
  story_ditch: ['place:ditch', 'nature:fire', 'virtue:sacrifice'],
  story_donkey_books: ['animal:donkey'],
  story_dog_parable: ['animal:dog'],
  story_ant_hoopoe: [
    'animal:ant',
    'animal:hoopoe',
    'miracle:ant_speech',
    'miracle:hoopoe_speech',
  ],
  story_bilqis: [
    'role:queen',
    'object:throne',
    'place:sheba',
    'miracle:throne_transport',
  ],
  story_blind_seeing: ['miracle:healing_blind'],
  story_light_parable: ['nature:sky', 'object:scripture'],
  story_rain_parable: ['nature:rain', 'nature:water', 'nature:plant'],
  story_charity_parable: ['virtue:charity', 'nature:plant'],
  story_haman: ['place:egypt', 'vice:tyranny'],
  story_empty_village: [
    'place:village',
    'animal:donkey',
    'miracle:dead_revived',
  ],
  story_ibrahim_birds: [
    'animal:birds',
    'miracle:dead_revived',
    'miracle:bird_creation',
  ],
  // --- Sirah & historical -----------------------------------------------
  story_isra_miraj: ['event:isra_miraj', 'place:masjid_al_haram', 'place:masjid_al_aqsa'],
  story_hijrah: ['event:hijrah', 'place:makkah', 'place:madinah'],
  story_badr: ['event:battle', 'place:badr'],
  story_uhud: ['event:battle', 'place:uhud'],
  story_hudaybiyyah: ['event:treaty', 'place:hudaybiyyah'],
  story_conquest_makkah: ['event:conquest', 'place:makkah'],
  story_qiblah_change: ['event:qiblah_change', 'place:makkah', 'place:masjid_al_haram'],
  story_tabuk: ['event:expedition', 'place:tabuk'],
  story_najran: ['event:mubahala', 'place:najran'],
  story_romans_persians: ['event:battle'],
  story_ancient_egypt: ['place:egypt'],
  story_madyan: ['place:madyan', 'place:thicket'],
  story_thamud: ['animal:camel', 'miracle:she_camel', 'place:hijr', 'vice:arrogance'],
  // --- Unseen continued --------------------------------------------------
  story_signs_hour: ['afterlife:hour'],
  story_trumpet: ['afterlife:trumpet'],
  story_mizan: ['afterlife:mizan'],
  story_araf_people: ['afterlife:araf'],
  story_paradise: ['afterlife:paradise'],
  story_hell: ['afterlife:hell'],
  story_covenant_souls: ['afterlife:covenant_souls'],
  story_iblis_refusal: ['vice:arrogance', 'vice:disobedience'],
  story_samiri: ['object:calf_gold', 'animal:calf', 'vice:idolatry'],
  story_asiya: ['family:husband_wife', 'role:wife_of_tyrant', 'virtue:patience'],
  story_mother_musa: ['family:mother', 'nature:water', 'place:egypt'],
  story_zulaykha: ['family:husband_wife', 'place:egypt', 'vice:betrayal'],
  story_believer_firaun: ['role:disbeliever', 'virtue:courage', 'place:egypt'],
  story_khidr: [
    'object:ship',
    'family:parent_child',
    'virtue:wisdom',
    'virtue:patience',
  ],
  story_three_messengers: ['place:village', 'role:messenger'],
  story_two_men: ['place:two_gardens', 'nature:plant', 'vice:arrogance'],
  story_saba: ['place:sheba', 'event:flood', 'nature:water', 'vice:disbelief'],
  story_ad: ['place:ad_lands', 'nature:wind', 'vice:arrogance'],
  story_nuh_people: ['event:flood', 'vice:disbelief'],
  story_intercession: ['afterlife:intercession', 'afterlife:judgment_day'],
  story_creation_heavens_earth: ['event:creation', 'nature:sky'],
  story_village_fish: [
    'animal:fish',
    'place:sea',
    'miracle:transformation_monkeys',
    'vice:disobedience',
  ],
  story_bani_israel: [
    'object:tablets',
    'object:manna_salwa',
    'event:exodus',
    'event:revelation',
    'vice:disobedience',
  ],
  story_yaqub: [
    'family:father',
    'family:son',
    'virtue:patience',
    'role:prophet',
  ],
  story_harut_marut: ['vice:deception'],
  story_sleepers_numbers: ['place:cave', 'miracle:cave_sleep'],
  story_wife_nuh: ['family:husband_wife', 'role:wife_of_prophet', 'vice:disbelief'],
  story_wife_lut: ['family:husband_wife', 'role:wife_of_prophet', 'vice:disbelief'],
  story_son_nuh: ['family:father', 'family:son', 'event:flood', 'vice:disbelief'],
  story_tree_cursed: ['object:tree_zaqqum', 'nature:plant', 'afterlife:hell'],
  story_seven_sleepers_dog: ['animal:dog', 'place:cave'],
  story_musa_firaun_dialogue: ['event:dialogue', 'place:egypt', 'vice:tyranny'],
  story_magicians: [
    'role:magician',
    'object:staff',
    'miracle:staff_to_serpent',
    'place:egypt',
    'virtue:repentance',
  ],
  story_sea_crossing: [
    'miracle:sea_parting',
    'place:sea',
    'nature:water',
    'event:exodus',
  ],
  story_golden_calf: [
    'animal:calf',
    'object:calf_gold',
    'vice:idolatry',
  ],
  story_musa_mountain: [
    'place:mount_sinai',
    'nature:mountain',
    'object:tablets',
    'event:revelation',
  ],
  story_sulayman_jinn: ['role:king'],
  story_dawud_trial: ['event:judgment', 'virtue:justice', 'role:king', 'animal:sheep'],
  story_ibrahim_fire: ['miracle:fire_cool', 'nature:fire', 'virtue:trust_in_allah'],
  story_ibrahim_stars: ['nature:stars', 'nature:moon', 'nature:sun'],
  story_ibrahim_nimrod: ['role:king', 'event:dialogue', 'vice:tyranny'],
  story_musa_midian: ['place:madyan', 'family:husband_wife'],
  story_musa_burning_bush: [
    'nature:fire',
    'place:mount_sinai',
    'event:revelation',
    'miracle:staff_to_serpent',
  ],
  story_isa_miracles: [
    'animal:birds',
    'miracle:bird_creation',
    'miracle:dead_revived',
    'miracle:healing_blind',
    'miracle:healing_leper',
    'object:table_spread',
  ],
  story_isa_ascension: ['nature:sky'],
  story_maryam_birth: ['family:mother', 'family:daughter', 'place:masjid_al_aqsa'],
  story_yusuf_dream: ['event:dream', 'nature:stars', 'nature:moon', 'nature:sun'],
  story_yusuf_prison: ['place:prison', 'event:dream'],
  story_yusuf_brothers: ['family:brothers', 'object:shirt_yusuf', 'object:cup', 'vice:jealousy'],
  story_abasa: ['virtue:humility'],
  story_abu_lahab: ['vice:disbelief', 'family:husband_wife'],
  story_sulayman_horses: ['animal:horse', 'role:king'],
  story_sulayman_trial: ['role:king', 'event:trial'],

  // --- Didactic mentions added later -----------------------------------
  // Stories whose Quranic basis is a short didactic mention rather than a
  // multi-segment narrative. They are still real Quran content and benefit
  // from being browseable under the animal facet alongside the cow,
  // elephant, ant, spider, fly, etc.
  story_bee: [
    'animal:bee',
    'nature:plant',
    'event:revelation',
    'virtue:knowledge',
  ],
};
